/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","knockout","jqueryui-amd/widget"],function(b,f,a){function d(){this.Init()}function c(a,b){var d={};d.value=b.value;return d}function e(a,b){var d={},c=b.optionMetadata;c&&"shouldWrite"===c.writeback&&(d[b.option]=b.value);return d}function g(b,d){return function(c){var g,e;g=c.parentElement;e=b.createChildContext(c.data,null,function(a){a.$optionContext=c});a.renderTemplate(d,e,null,g);return null}}function h(a,b,d){return"optionTemplate"===a&&null!==b?{optionRenderer:g(d,
String(b))}:null}function k(b,d){return function(c){var g=b.createChildContext(c.data);a.renderTemplate(d,g,{afterRender:function(a){f(a)._ojDetectCleanData()}},c.parentElement);return null}}function l(a,b,d){if("areaLayers"===a){for(a=0;a<b.length;a++){var c=b[a].areaDataLayer;if(c){var g=c.template;null!=g&&(c._templateRenderer=k(d,g))}}return{areaLayers:b}}if("pointDataLayers"===a){for(a=0;a<b.length;a++)g=b[a].template,null!=g&&(b[a]._templateRenderer=k(d,g));return{pointDataLayers:b}}return null}
function p(a,b){this.Init(a,b)}function n(b,d){return function(c){var g=b.createChildContext(c.data);a.renderTemplate(d,g,{afterRender:function(a){f(a)._ojDetectCleanData()}},c.parentElement);return null}}function m(a,b,d,c){if(null==d)return null;var g=q(d);null!=g&&(d=s(a,g,c,b,d));return d}function q(a){a=Object.keys(a);for(var d=-0;d<a.length;d++){var c=a[d];if(b.pa.dra(c))return c}return null}function s(a,d,c,g,e){a=v(a,d,c,g);c=a.wxa;if(null==c)return e;var h={};w(c,function(a,b){h[a]=b});e=
b.Zc.sg({},e);e[d]=r(g,h,a.yxa);return e}function r(a,d,c){function g(){var c={};Object.keys(d).forEach(function(g){var e=b.pa.G0(d[g]).bind(null,a);Object.defineProperty(c,g,{get:e,enumerable:!0})});Object.defineProperty(c,b.pa.lZ,{value:d});return c}g.toString=function(){return c};return g}function u(a,b,d){var c=b.getBindingsString;if(c)return c.call(b,a,d);switch(a.nodeType){case 1:return a.getAttribute("data-bind");case 8:return(a=a.nodeValue.match(/^\s*ko(?:\s+([\s\S]+))?\s*$/))?a[1]:null}return null}
function v(b,d,c,g){var e=null;b=u(b,c,g);b=a.jsonExpressionRewriting.parseObjectLiteral(b);var h=null;w(b,function(a,b){return a===d?(h=b,!0):!1});null!=h&&0===h.indexOf("{")&&(e=a.jsonExpressionRewriting.parseObjectLiteral(h));return{wxa:e,yxa:h}}function w(a,b){for(var d=0;d<a.length;d++){var c=a[d],g=c.key,c=c.value;if(null!=g&&null!=c&&b(g.trim(),c.trim()))break}}function t(a,b,d,c){var g=a[d];null!=g&&(b[d]=function(){var b=g.apply(a,arguments);if(null!=c){var d=Array.prototype.slice.call(arguments);
d.push(b,a);b=c.apply(null,d)}return b})}function x(b,d){return function(c){var g,e;g=c.parentElement;e=b.createChildContext(c.data,null,function(a){a.$key=c.key;a.$metadata=c.metadata;a.$headerContext=c});a.renderTemplate(d,e,{afterRender:function(a){f(a)._ojDetectCleanData()}},g);return null}}function y(b,d){return function(c){var g,e;g=c.parentElement;e=b.createChildContext(c.data,null,function(a){a.$keys=c.keys;a.$metadata=c.metadata;a.$cellContext=c});a.renderTemplate(d,e,{afterRender:function(a){f(a)._ojDetectCleanData()}},
g);return null}}function B(b,d,c){var g={};(function(d,c){g=function(g){var e=null,h=null;"header"==c?(e=b.extend({$columnIndex:g.columnIndex,$headerContext:g.headerContext,$data:g.data}),h=g.headerContext.parentElement):"cell"==c&&(e=b.createChildContext(g.row,null,function(a){a.$columnIndex=g.columnIndex;a.$cellContext=g.cellContext}),h=g.cellContext.parentElement);"footer"==c&&(e=b.extend({$columnIndex:g.columnIndex,$footerContext:g.footerContext}),h=g.footerContext.parentElement);a.renderTemplate(d,
e,{afterRender:function(a){f(a)._ojDetectCleanData()}},h,"replaceNode")}})(c,d);return g}function C(b,d){return function(c){var g=b.createChildContext(c.row,null,function(a){a.$rowContext=c.rowContext});a.renderTemplate(d,g,{afterRender:function(a){f(a)._ojDetectCleanData()}},c.rowContext.parentElement,"replaceNode")}}function M(b,c){return function(d){var g,e;g=d.parentElement;e=b.createChildContext(d.data,null,function(a){a.$itemContext=d});a.renderTemplate(c,e,{afterRender:function(a){f(a)._ojDetectCleanData()}},
g,"replaceNode");return null}}function G(a,b,d){return"item"==a?(a=b.template,null!=a&&(b.renderer=M(d,a)),{item:b}):null}b.b.la(d,b.b,"ComponentBinding.GlobalChangeQueue");d.prototype.Init=function(){d.p.Init.call(this);this.kI=[];this.tB=[]};d.prototype.xBa=function(a){-1===this.kI.indexOf(a)&&(this.kI.push(a),this.wF||(this.wF=setTimeout(b.b.t$(this,this.j1),1)))};d.prototype.RT=function(){this.wF&&clearTimeout(this.wF);this.j1()};d.prototype.j1=function(){var a;this.wF=null;var b=this.kI;this.kI=
[];for(a=0;a<b.length;a++){var d=b[a];this.tB.push({vW:d,gr:d.Lya()})}for(;0<this.tB.length;)a=this.tB.shift(),a.vW.mxa(a.gr)};b.pa=function(a,b){this.Init(a,b)};o_("ComponentBinding",b.pa,b);b.b.la(b.pa,b.b,"oj.ComponentBinding");b.pa.create=function(d,c){if(null==d)throw"Binding name is required!";var g=new b.pa(d,c),e=a.bindingHandlers,h,k=Array.isArray(d)?d:[d];for(h=0;h<k.length;h++){var f=k[h];b.pa.AZ.push(f);e[f]=g}return g};o_("ComponentBinding.create",b.pa.create,b);b.pa.Ji=function(){return b.pa.yga};
o_("ComponentBinding.getDefaultInstance",b.pa.Ji,b);b.pa.prototype.Ti=function(a){var b=a["for"],b=null==b?"@global":b,d=this.jH[b]||[];d.push(a);this.jH[b]=d};b.b.g("ComponentBinding.prototype.setupManagedAttributes",{Ti:b.pa.prototype.Ti});b.pa.RT=function(){b.pa.b0.RT()};o_("ComponentBinding.deliverChanges",b.pa.RT,b);b.pa.prototype.Init=function(a,d){b.pa.p.Init.call(this);"string"===typeof d&&(d={componentName:d});this.cN=d||{};Array.isArray(a);this.init=this._init.bind(this);this.update=this.Xq.bind(this);
this.jH={}};b.pa.prototype._init=function(b,d,c,g,e){a.applyBindingsToDescendants(e,b);return{controlsDescendantBindings:!0}};b.pa.prototype.Xq=function(d,c,g,e,h){function k(a){l.forEach(function(a){a.dispose()});l=[];a&&n&&(n("destroy"),n=null);q&&(q.Ix(),q=null);u.off(b.pa.VL)}function r(a,c,e){if(null!=a){var k=u[a];if("function"!==typeof k)b.r.error("Component %s is not found",a);else{k=k.bind(u);q=new p(k,b.pa.b0);var f=Object.keys(e).filter(function(a){return!(null==a||a===c)});n=this.mqa(d,
{T:k,jC:q,o$:a,vD:f,Txa:l,Ur:function(){return e},zx:g,Yt:h,uya:function(){n=null}})}}}var l=[],m=0,n,q,u=f(d);a.ignoreDependencies(function(){a.computed(function(){var d=a.utils.unwrapObservable(c());"object"!==typeof d&&b.r.error("ojComponent binding should evaluate to an object");var g=this.cN.componentName,e,h=!1;if(null==g&null!=d){for(var f=[b.pa.Mfa,"role"],l=0;!h&&l<f.length;l++)e=f[l],e in d&&(h=!0,g=d[e]);h||b.r.error("component attribute is required for the ojComponent binding");g=a.utils.unwrapObservable(g)}0==
m?m=1:a.ignoreDependencies(k,this,[!0]);a.ignoreDependencies(r,this,[g,e,d])},this,{disposeWhenNodeIsRemoved:d})},this);a.utils.domNodeDisposal.addDisposeCallback(d,k.bind(this,[!1]))};b.pa.prototype.mqa=function(d,c){function g(){var a=this.cta,f=b.pa.owa(c.Ur()[a]);if(0===h){var r=n[a];null!=r?(k[a]=r,r=r.Yo,null!=r&&(a=r(a,f,d,l,c.Ur,c.zx,c.Yt)||{},b.Zc.sg(u,a))):u[a]=f}else if(!e)if(null!=n[a]){if(r=n[a].update,null!=r)for(a=r(a,f,d,l,c.Ur,c.zx,c.Yt)||{},f=Object.keys(a),r=0;r<f.length;r++){var p=
f[r];c.jC.M9(p,a[p])}}else c.jC.M9(a,f)}var e=!1,h=0,k={},r=f(d),l=c.T,p=c.o$,m=this;r.on("ojdestroy"+b.pa.VL,function(a){a.target&&a.target==d&&(c.uya(),(a=m.cN.beforeDestroy)&&a(d,l,c.Ur,c.zx,c.Yt),b.pa.k1(!1,k,d,l,c.Ur,c.zx,c.Yt),e=!0,c.jC.Ix())});var n=b.pa.B7(this.jH,c.vD,p),q=b.pa.Ji();this!==q&&(p=q.Ina(c.vD,p),b.Zc.sg(p,n),n=p);for(var u={},p=0;p<c.vD.length;p++)c.Txa.push(a.computed(g,{cta:c.vD[p]}));h=1;b.pa.Fta(r,c);r=b.pa.K1(u);p=Object.keys(r);p.forEach(function(a){delete u[a]});l(u);
for(q=0;q<p.length;q++){var s=p[q];l("option",s,r[s])}(r=this.cN.afterCreate)&&r(d,l,c.Ur,c.zx,c.Yt);b.pa.k1(!0,k,d,l,c.Ur,c.zx,c.Yt);u=null;return l};b.pa.G0=function(a){return new Function("$context","with($context){with($data||{}){return "+a+";}}")};b.pa.prototype.Ina=function(a,d){return b.pa.B7(this.jH,a,d)};b.pa.B7=function(a,b,d){function c(b,d){var g=a[b];if(null!=g)for(var h=g.length-1;0<=h;h--){var k=g[h];null!=k.attributes&&e.push(k);if(d&&(k=k.use,null!=k))for(var k=Array.isArray(k)?k:
[k],f=0;f<k.length;f++)c(k[f],!0)}}var g={},e=[];c(d,!0);d=f.oj[d];if(null!=d)for(d=Object.getPrototypeOf(d.prototype);null!=d&&"oj"===d.namespace;)c(d.widgetName,!0),d=Object.getPrototypeOf(d);c("@global",!1);if(0<e.length)for(d=0;d<b.length;d++)for(var h=b[d],k=0;k<e.length;k++){var r=e[k];if(0<=r.attributes.indexOf(h)){g[h]={Yo:r.init,update:r.update,xx:r.afterCreate,xxa:r.beforeDestroy};break}}return g};b.pa.VL=".oj_ko";b.pa.Fta=function(a,d){for(var g={"^slider$":[{event:"slidechange",getter:c}],
"^oj*":[{event:"ojoptionchange",getter:e}]},h={},k=Object.keys(g),f=0;f<k.length;f++){var r=k[f];if(d.o$.match(r)){g=g[r];for(k=0;k<g.length;k++)f=g[k],a.on(f.event+b.pa.VL,{rza:f.getter},function(c,g){if(c.target===a[0]){var e=c.data.rza(c,g),k=d.Ur(),f;for(f in e){d.jC.jCa(f);try{if(0<=d.vD.indexOf(f)){var r=k[b.pa.lZ];b.pa.dxa(f,k[f],e[f],null==r?null:r[f],d.Yt,h)}}finally{d.jC.OBa(f)}}}});break}}};b.pa.coa=function(a){var b=["true","false","null","undefined"];if(null==a||0<=b.indexOf(a))return null;
b=a.match(/^(?:[$_a-z][$\w]*|(.+)(\.\s*[$_a-z][$\w]*|\[.+\]))$/i);return null===b?null:"function(v){"+(b[1]?"Object("+b[1]+")"+b[2]:a)+"\x3dv;}"};b.pa.dxa=function(d,c,g,e,h,k){null!=c&&a.isObservable(c)?a.isWriteableObservable(c)&&c(g):(d in k||(c=null,e=b.pa.coa(e),null!=e&&(c=b.pa.G0(e)),k[d]=c),(d=k[d])&&d(h)(g))};b.pa.owa=function(d){d=a.utils.unwrapObservable(d);(Array.isArray(d)||b.Zc.isPlainObject(d))&&d.ojConvertToJS&&(d=a.toJS(d));return d};b.pa.K1=function(a){for(var b={},d=Object.keys(a),
c=0;c<d.length;c++){var g=d[c];0<=g.indexOf(".")&&(b[g]=a[g])}return b};b.pa.k1=function(a,b,d,c,g,e,h){for(var k=Object.keys(b),f=0;f<k.length;f++){var r=k[f],l=b[r];(l=a?l.xx:l.xxa)&&l(r,d,c,g,e,h)}};b.pa.b0=new d;b.pa.jia=function(){return b.Tv()&&a?a.version:""};b.pa.dra=function(a){return 0<=b.pa.AZ.indexOf(a)};b.pa.AZ=[];b.pa.Mfa="component";b.pa.lZ="_ojOptions";(function(){var d=a.removeNode;a.removeNode=function(a){var c=b.Components;c&&b.A.yda(a);try{d(a)}finally{c&&b.A.yda(null)}}})();b.pa.yga=
b.pa.create(["ojComponent","jqueryUI"]);f.widget("oj._ojDetectCleanData",{_destroy:function(){a.cleanNode(this.element[0])}});b.pa.Ji().Ti({attributes:["optionTemplate"],init:function(a,b,d,c,g,e,k){a=h(a,b,k);if(null!==a)return a},update:function(a,b,d,c,g,e,k){return h(a,b,k)},"for":"ComboboxOptionRenderer"});b.pa.Ji().Ti({"for":"ojCombobox",use:"ComboboxOptionRenderer"});b.pa.Ji().Ti({"for":"ojSelect",use:"ComboboxOptionRenderer"});b.pa.Ji().Ti({"for":"ojInputSearch",use:"ComboboxOptionRenderer"});
b.dm={};o_("ResponsiveKnockoutUtils",b.dm,b);b.dm.Gx=function(b){if(null==b)throw Error("oj.ResponsiveKnockoutUtils.createMediaQueryObservable: aborting, queryString is null");b=window.matchMedia(b);var d=a.observable(b.matches);b.addListener(function(a){d(a.matches)});-1!=navigator.userAgent.indexOf("WebKit")&&-1==navigator.userAgent.indexOf("Chrome")&&f(window).resize(function(){0===f("body").has(".oj-webkit-bug-123293").length&&f("body").append('\x3cdiv aria-hidden\x3d"true" class\x3d"oj-helper-hidden-accessible oj-webkit-bug-123293"\x3e');
f(".oj-webkit-bug-123293").text((new Date).getMilliseconds().toString())});return d};o_("ResponsiveKnockoutUtils.createMediaQueryObservable",b.dm.Gx,b);b.dm.aya=function(){var d=b.Pb.Nx(b.Pb.dv.XXL_UP),c=b.Pb.Nx(b.Pb.dv.XL_UP),g=b.Pb.Nx(b.Pb.dv.LG_UP),e=b.Pb.Nx(b.Pb.dv.MD_UP),h=b.Pb.Nx(b.Pb.dv.SM_UP),k=null==d?null:b.dm.Gx(d),f=null==c?null:b.dm.Gx(c),r=null==g?null:b.dm.Gx(g),l=null==e?null:b.dm.Gx(e),p=null==h?null:b.dm.Gx(h);return a.computed(function(){if(k&&k())return b.Pb.Tk.XXL;if(f&&f())return b.Pb.Tk.XL;
if(r&&r())return b.Pb.Tk.LG;if(l&&l())return b.Pb.Tk.MD;if(p&&p())return b.Pb.Tk.SM;throw Error(" NO MATCH in oj.ResponsiveKnockoutUtils.createScreenRangeObservable");})};o_("ResponsiveKnockoutUtils.createScreenRangeObservable",b.dm.aya,b);b.pa.Ji().Ti({attributes:["areaLayers","pointDataLayers"],init:function(a,b,d,c,g,e,h){return l(a,b,h)},update:function(a,b,d,c,g,e,h){return l(a,b,h)},"for":"ojThematicMap"});a.bindingHandlers.ojContextMenu={update:function(d,c){function g(a,b,d){q=d;var c=k();
if(q)l.one("touchend.ojContextMenu",function(){c.Rv(!0);setTimeout(function(){c.Rv(!1)},50)});"touchstart"===v&&"contextmenu"===a.type||"contextmenu"===v&&"touchstart"===a.type?(v=null,clearTimeout(s)):!a.isDefaultPrevented()&&(b={launcher:l,initialFocus:"menu",position:{mouse:{my:"start top",at:"start bottom",of:a},touch:{my:"start\x3e40 center",at:"start bottom",of:a,collision:"flipfit"},keyboard:{my:"start top",at:"start bottom",of:"launcher"}}[b]},c.OE=!0,c.open(a,b),c.OE=!1,h().is(":visible")&&
(a.preventDefault(),document.addEventListener("keyup",e),"touchstart"===a.type||"contextmenu"===a.type))&&(v=a.type,s=setTimeout(function(){v=null},300))}function e(a){121==a.which&&a.shiftKey&&h().is(":visible")&&a.preventDefault()}function h(){p||r();return p}function k(){m||r();return m}function r(){p=f(t).first();m=p.data("oj-ojMenu");if(!m)throw Error('"contextMenu" set to "'+t+'", which does not reference a valid JET Menu.');p.on("ojclose.ojContextMenu",function(){document.removeEventListener("keyup",
e)})}var l=f(d),p,m,n,q=!1,u=!1,s,v=null,w;l.off(".ojContextMenu").removeClass("oj-menu-context-menu-launcher")[0].removeEventListener("click",w,!0);p&&p.off(".ojContextMenu");clearTimeout(n);p=m=void 0;var t=a.utils.unwrapObservable(c());f.isPlainObject(t)&&(t=d.getAttribute("contextmenu"))&&(t=document.getElementById(t));w=function(a){if(q)return a.preventDefault(),a.stopPropagation(),q=!1};d.addEventListener("click",w,!0);l.on("touchstart.ojContextMenu mousedown.ojContextMenu keydown.ojContextMenu ",
function(a){if("mousedown"!==a.type||!k().Rv())return q=!1,"touchstart"===a.type&&(u=!0,n=setTimeout(g.bind(void 0,a,"touch",!0),750)),!0}).on("touchend.ojContextMenu touchcancel.ojContextMenu",function(){u=!1;clearTimeout(n);return!0}).on("keydown.ojContextMenu contextmenu.ojContextMenu",function(a){("contextmenu"===a.type||121==a.which&&a.shiftKey)&&g(a,u?"touch":"keydown"===a.type?"keyboard":"mouse",!1);return!0}).addClass(b.A.Zd()?"oj-menu-context-menu-launcher":"")}};b.b.la(p,b.b,"ComponentBinding.ComponentChangeTracker");
p.prototype.Init=function(a,b){p.p.Init.call(this);this.ra=a;this.tB=b;this.xN={};this.mx={}};p.prototype.M9=function(a,b){this.lra(a)||this.v1||(this.xN[a]=b,this.tB.xBa(this))};p.prototype.Ix=function(){this.v1=!0};p.prototype.OBa=function(a){var d=this.mx[a]||0;b.l.assert(0<d,"ComponentChangeTracker suspendCount underflow");d--;0==d?delete this.mx[a]:this.mx[a]=d};p.prototype.jCa=function(a){this.mx[a]=(this.mx[a]||0)+1};p.prototype.mxa=function(a){if(!this.v1){var d=b.pa.K1(a),c={changed:!0};
this.ra("option",a,c);for(var g in d)this.ra("option",g,d[g],c)}};p.prototype.Lya=function(){var a=this.xN;this.xN={};return a};p.prototype.lra=function(a){return 1<=(this.mx[a]||0)};b.pa.Ji().Ti({attributes:["template"],init:function(a,b,d,c,g,e,h){return"template"===a?{_templateFunction:n(h,b)}:null},update:function(a,b,d,c,g,e,h){return"template"===a?{_templateFunction:n(h,b)}:null},"for":"ojDiagram"});b.dV={};o_("koStringTemplateEngine",b.dV,b);b.dV.AAa=function(){if(!a.templates){var b={},d=
{},c=new a.nativeTemplateEngine,g=function(a){this.px=a;this.text=function(a){if(!a)return b[this.px];b[this.px]=a};this.data=function(a,b){d[this.px]||(d[this.px]={});if(1===arguments.length)return d[this.px][a];d[this.px][a]=b}};c.makeTemplateSource=function(b,d){if("string"==typeof b){d=d||document;var c=d.getElementById(b);return c?new a.templateSources.domElement(c):new g(b)}if(b&&1==b.nodeType||8==b.nodeType)return new a.templateSources.anonymousTemplate(b)};a.templates=b;a.setTemplateEngine(c)}};
o_("koStringTemplateEngine.install",b.dV.AAa,b);(function(){var d=a.bindingProvider,c=d.instance,d=d.instance={};t(c,d,"nodeHasBindings");t(c,d,"getBindings",function(a,d,c){a=c;d=q(c);null!=d&&(b.r.error("%s binding is not compatible with bidding providers not implementing getBindingAccessors()",d),a=b.Zc.sg({},c),delete a[d]);return a});t(c,d,"getBindingAccessors",m)})();b.pa.Ji().Ti({attributes:["header","cell"],init:function(a,b,d,c,g,e,h){if("header"===a)return a=b.row,null!=a&&(d=a.template,
null!=d&&(a.renderer=x(h,d))),a=b.column,null!=a&&(d=a.template,null!=d&&(a.renderer=x(h,d))),{header:b};if("cell"===a)return a=b.template,null!=a&&(b.renderer=y(h,a)),{cell:b}},update:function(a,b,d,c,g,e,h){return"header"===a?(a=b.row,null!=a&&(d=a.template,null!=d&&(a.renderer=x(h,d))),a=b.column,null!=a&&(d=a.template,null!=d&&(a.renderer=x(h,d))),{header:b}):"cell"===a?(a=b.template,null!=a&&(b.renderer=y(h,a)),{cell:b}):null},"for":"ojDataGrid"});b.pa.Ji().Ti({attributes:["columns","columnsDefault",
"rowTemplate"],init:function(a,b,d,c,g,e,h){if("columns"==a||"columnsDefault"==a){for(d=0;d<b.length;d++){var k=b[d];c=k.template;g=k.footerTemplate;e=k.headerTemplate;null!=c&&(k.renderer=B(h,"cell",c));null!=g&&(k.footerRenderer=B(h,"footer",g));null!=e&&(k.headerRenderer=B(h,"header",e))}return"columns"==a?{columns:b}:{columnsDefault:b}}if("rowTemplate"==a)return{rowRenderer:C(h,b)}},update:function(a,b,d,c,g,e,h){if("columns"==a||"columnsDefault"==a){var k;for(d=0;d<b.length;d++){var f=b[d];g=
f.template;e=f.footerTemplate;k=f.headerTemplate;null!=g&&(f.renderer=B(h,"cell",g));null!=e&&(f.footerRenderer=B(h,"footer",e));null!=k&&(f.headerRenderer=B(h,"header",k))}"columns"==a?c({columns:b}):c({columnsDefault:b})}else if("rowTemplate"==a)return{rowRenderer:C(h,b)};return null},"for":"ojTable"});b.pa.Ji().Ti({attributes:["item"],init:function(a,b,d,c,g,e,h){a=G(a,b,h);if(null!=a)return a},update:function(a,b,d,c,g,e,h){return G(a,b,h)},"for":"ojListViewRenderer"});b.pa.Ji().Ti({"for":"ojListView",
use:"ojListViewRenderer"});b.pa.Ji().Ti({"for":"ojNavigationList",use:"ojListViewRenderer"})});