/**
 * Copyright (c) 2014, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(['./DvtToolkit', './DvtSubcomponent'], function(dvt) {
  // Internal use only.  All APIs and functionality are subject to change at any time.
  
  // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  
D.BR=(0,D.t)();(0,D.da)("DvtBaseTreeView",D.BR);D.z.l(D.BR,D.sj,"DvtBaseTreeView");D.BR.prototype.Init=function(a,b,c){D.BR.o.Init.call(this,a,b,c);this.eb=this.uI(this,a,this.dispatchEvent,this);this.eb.me(this);this.Hd=new D.ou(a);this.wl=new D.bV(this);(0,D.Oq)(this.eb,this.Hd);this.wb=D.o;this.ela=D.p;this.iQ=D.o};D.BR.prototype.vd=function(a){a?(this.D=this.rf.Vj(a),(0,D.Zk)()||(this.D.animationOnDisplay="none",this.D.animationOnDataChange="none")):this.D||(this.D=(0,D.zj)(this))};
D.BR.prototype.P=function(a,b,c){var d=a||!this.D;this.vd(a);var e=this.q();if(e.nodes==D.o)a=D.o;else{a=[];for(var f=D.H.ZG(e.hiddenCategories),g=0;g<e.nodes.length;g++){var h=e.nodes[g];h._index=g;(h=(0,D.iV)(this,f,h))&&a.push(h)}if(1==a.length)a=a[0];else{for(var g=e=0;g<a.length;g++)e+=a[g].Tc();g=this.Xp({value:e,gHa:D.k});g.S0(a);a=g}}this.hN({root:a});!(0,window.isNaN)(b)&&!(0,window.isNaN)(c)&&(this.Ga=b,this.Ta=c);this.eb&&this.eb.Cc();c=new D.A(0,0,this.Ga,this.Ta);this.bq(c);b=new D.D(this.j());
this.k(b);this.cZ&&(this.Fc=new D.Lg(this.j(),this.eb),this.Fc.dL=D.k);this.Ij(b,c);this.mr&&(this.i1=D.k,this.mr.stop());a=this.q().animationOnDataChange;g=new D.A(0,0,this.Ga,this.Ta);c=D.p;this.X?a&&d&&(D.dl.isSupported(a)?(this.mr=D.dl.qD(this.j(),a,this.X,b,g,this.nI),c=D.k):this.sQ&&"auto"==a&&(this.mf=this.a2(),this.k(this.mf),a=new D.ZU(this.j(),this.mf),g=this.sQ,e=this.Ka,f=this.PX,h=this.cJ,a.pO=D.p,a.sQ=g,a.PX=f,(0,D.$U)(h,g)||(0,D.$U)(f,e)?(a.pO=D.k,f=(0,D.fS)(g),h=(0,D.fS)(e),f.push(g),
h.push(e),(0,D.Tm)(a,f,h)):(0,D.Tm)(a,[g],[e]),this.mr=a.Oq(D.k))):this.mr=this.b2(b,g);this.PX=this.sQ=D.o;this.mr&&(this.eb.gi(this),this.mr.ie(this.sr,this),this.mr.play());c?this.Og=this.X:this.X&&this.removeChild(this.X);this.X=b;d?this.cA():this.m3();(0,D.jV)(this,!this.mr);this.mr||(0,D.kV)(this);this.Sn()};D.BR.prototype.render=D.BR.prototype.P;D.BR.prototype.AE=(0,D.ca)(D.o);D.BR.prototype.bq=(0,D.t)();D.BR.prototype.Ij=(0,D.t)();
D.HR=function(a,b){var c=new D.Te(a.j(),0,0,a.Ga,a.Ta);(0,D.wi)(c);b.k(c)};D.ER=function(a,b){if(0<a.cJ.length){var c=a.Ka?a.Ka.Nc():D.o;a.bn&&(0,D.Xr)(a.eb,a.bn.ka());a.bn=D.lV.P(a,b,a.cJ,c);(0,D.Yr)(a.eb,a.bn.ka())}else a.bn&&(0,D.Xr)(a.eb,a.bn.ka()),a.bn=D.o};D.LR=function(a,b){var c=a.q(),d=c.emptyText;d||(d=(0,D.nk)(c,"labelNoData","DvtUtilBundle","NO_DATA"));D.$e.Om(b,d,new D.A(0,0,a.Ga,a.Ta),a.ka(),c._statusMessageStyle)};D.IR=function(a){return a.Ka&&0<a.Ka.Tc()};D.x=D.BR.prototype;
D.x.b2=function(a,b){var c=this.q().animationOnDisplay;return D.dl.isSupported(c)?D.dl.by(this.j(),c,a,b,this.nI):D.o};D.x.sr=function(){this.mf&&(this.removeChild(this.mf),this.mf=D.o);this.Og&&(this.removeChild(this.Og),this.Og=D.o);this.i1=D.p;this.mr=D.o;this.eb.me(this);(0,D.jV)(this,D.k);(0,D.kV)(this)};D.x.a2=function(){return new D.D(this.j())};D.x.xw=function(a){return new D.gV(a)};D.x.uI=function(a,b,c,d){return new D.WR(a,b,c,d)};D.x.Tea=function(a){if(a&&a.WB){var b=a.zc();if(b&&0<b.length)return b[0]}return a};
D.x.Ge=function(a){this.q().highlightedCategories=D.pl.Y(a);(0,D.ql)(a,D.fV.MR(this.Ka),"any"==this.q().highlightMatch)};D.BR.prototype.highlight=D.BR.prototype.Ge;D.BR.prototype.select=function(a){var b=this.q();b.selection=D.pl.Y(a);this.Hb&&(a=D.fV.MR(this.Ka),(0,D.Il)(this.Hb,b.selection,a))};D.BR.prototype.select=D.BR.prototype.select;D.BR.prototype.ka=(0,D.v)("eb");
D.BR.prototype.hN=function(a){var b=this.q();this.sQ=this.Ka;this.PX=this.cJ;this.Ka=a.root;this.cJ=b._ancestors?b._ancestors:[];this.Yr=this.Ka?D.fV.Vpa(this.Ka):0;this.ut=this.Ka?D.fV.Upa(this.Ka,0):0;this.nI=(0,D.hp)(b.animationDuration)/1E3;this.jQa=a.aOa?a.aOa:{};(this.t8="none"==b.selectionMode?D.o:"single"==b.selectionMode?"s":"m")?(this.Hb=new D.$k(this.t8),this.l7=b.selection):this.Hb=D.o;this.eb.yu(this.Hb);(0,D.xj)(this.eb,this.xw(this.eb));this.wX=D.o;this.kia=[];if(b.attributeGroups){a=
D.fV.MR(this.Ka);for(var c=0;c<b.attributeGroups.length;c++){var d=b.attributeGroups[c],e=D.o;if("continuous"==d.attributeType)D.fV.lHa(d,a),e=new D.hR(d.min,d.max,d.minLabel,d.maxLabel,d.colors);else for(var e=new D.iR,f=0;f<d.groups.length;f++){var g=d.groups[f];e.add(g.id,g.label,{color:g.color,pattern:g.pattern})}this.kia.push({dHa:e,$Na:d.S,id:d.id});!b._adf&&!b._legendSource&&0==c?this.wX=e:b._legendSource&&b._legendSource==d.id&&(this.wX=e)}D.fV.lNa(this.kia,a)}if((a=b._contextMenus)&&0<a.length)this.eb.lN=
new D.cw(this.j(),a);if(b=b._templates){this.cZ={};for(var h in b)a=D.ze.cT(b[h]),this.cZ[h]=a}};D.BR.prototype.m3=function(){for(var a=this.Hb?this.Hb.getSelection():[],b=0;b<a.length;b++)a[b].jb(D.k)};D.BR.prototype.cA=function(){if(this.Hb&&this.l7){var a=D.fV.MR(this.Ka);(0,D.Il)(this.Hb,this.l7,a);this.l7=D.o}};D.kV=function(a){var b=a.q().highlightedCategories;b&&0<b.length&&a.Ge(b)};
D.jV=function(a,b){var c=D.o,d=a.iQ;d&&(c=(0,D.hV)(a.Ka,d),a.eb.ws(c));b&&(a.iQ=D.o);c||(c=a.Tea(a.Ka),a.eb.ws(c));b&&a.Op(a.a0())};D.x=D.BR.prototype;D.x.Op=function(a){this.ela=a;this.eb.Op(a)};D.x.a0=(0,D.v)("ela");D.x.LE=function(a,b){return this.Ka.AD(a,b)};D.x.YI=function(a){return this.Hb?a[0]:D.o};D.x.RB=function(a){a.Da()||(this.Hb.Nm(a,D.p),this.eb.Nv());a=[];for(var b=this.Hb.getSelection(),c=0;c<b.length;c++)a.push(b[c].getId());return a};
D.x.QB=function(){for(var a=[],b=this.Hb.getSelection(),c=0;c<b.length;c++)a.push(b[c].ia());return a};D.x.Hu=function(a){this.Cf&&(this.removeChild(this.Cf),this.Cf=D.o);if(a&&(this.Cf=a.iH()))a=this.q().styleDefaults,this.Cf.pa(a._dropSiteFillColor,a._dropSiteOpacity),this.Cf.Ra(a._dropSiteBorderColor),this.k(this.Cf);return this.Cf};D.x.lza=function(a){a instanceof D.at&&(0,D.eV)(this,a.getId(),D.p)};
D.eV=function(a,b,c){c&&a.Ka&&b==a.Ka.getId()&&0<a.cJ.length?(a.iQ=b,a.dispatchEvent(new D.PC(a.cJ[0].id))):c||a.dispatchEvent(new D.PC(b));a.j().ge().Cc()};D.BR.prototype.dba=function(a){return(0,D.Ej)(this.eb,a)};D.BR.prototype.Xp=(0,D.ca)(D.o);D.BR.prototype.ZZ=(0,D.ca)(D.o);D.BR.prototype.Gf=function(){return new D.mV(this)};D.BR.prototype.getAutomation=D.BR.prototype.Gf;D.BR.prototype.Faa=(0,D.v)("bn");
D.iV=function(a,b,c){if(D.fV.kMa(b,c))return D.o;var d=a.Xp(c);if(d.Qa()){var e=[];c=c.nodes?c.nodes:[];for(var f=0;f<c.length;f++){var g=c[f];g._index=f;(g=(0,D.iV)(a,b,g))&&e.push(g)}d.S0(e)}return d};D.KR=function(a,b){if((0,D.Jf)()||(0,D.vf)())for(var c=D.fV.qIa(b),d=0;d<c.length-1;d++){var e=a.getId()+(c[d+1].getId()?c[d+1].getId():c[d+1].Nc()),e=e.replace(/\s+/g,"");c[d+1].ia().setId(e,D.k);c[d].ia().$b("flowto",e)}};
D.x=D.BR.prototype;D.x.zj=function(a,b,c){return this.Hd.zj(c)};D.x.yk=function(a,b){return this.Hd.yk(a,b)};D.x.$t=function(a,b){return this.Hd.$t(a,b)};D.x.xp=function(a,b){return this.Hd.xp(a,b)};D.x.Ov=function(a,b){return this.Hd.Ov(a,b)};D.x.Vv=function(a,b){return this.Hd.Vv(a,b)};D.x.$v=function(){this.Hd.$v()};D.x.es=function(){this.Hd.es()};
D.BR.prototype.ro=function(a,b,c){return this.wl.ro(a,b,c)};D.BR.prototype.ks=function(a,b){return this.wl.ks(a,b)};
D.ZU=function(a,b){this.Init(a,b)};D.z.l(D.ZU,D.Sm,"DvtBaseTreeAnimationHandler");D.$U=function(a,b){if(!b||!a)return D.p;for(var c=0;c<a.length;c++)if(a[c].id==b.getId())return D.k;return D.p};
D.bV=(0,D.ba)("H");D.z.l(D.bV,D.qu,"DvtBaseTreeDropTarget");D.bV.prototype.ro=function(a,b,c){if(a=this.H.LE(a,b))a!=this.uF&&(this.H.Hu(a),this.uF=a);else return this.H.Hu(D.o),D.o;return c[0]};D.bV.prototype.ks=function(a,b){var c=this.H.LE(a,b);return c?{sHa:c.getId()}:D.o};
D.WR=function(a,b,c,d){this.Init(b,c,d);this.H=a};D.z.l(D.WR,D.Pj,"DvtBaseTreeEventManager");D.x=D.WR.prototype;D.x.Ny=function(a){var b=(0,D.Ej)(this,a.target);b&&b.Aa&&b.Aa()&&(0,D.cV)(this,b,a.shiftKey)};D.x.Jh=function(a){D.WR.o.Jh.call(this,a);var b=(0,D.Ej)(this,a.target);(0,D.dV)(this,b);b&&(!b.Aa||!b.Aa())&&(0,D.cV)(this,b,a.shiftKey)};D.x.Oy=function(a){D.WR.o.Oy.call(this,a);(a=(0,D.Ej)(this,a.target))&&a.gu&&a.gu()};
D.x.Sm=function(a){D.WR.o.Sm.call(this,a);var b=(0,D.Ej)(this,a.target);b&&b.fu&&(a=(a=(0,D.Ej)(this,a.relatedTarget))&&a.getId?a.getId():D.o,(b.getId()==D.o||a!=b.getId())&&b.fu())};D.x.Kh=function(a){var b=D.p,b=this.dd();13==a.keyCode&&!a.ctrlKey?(b=this.dd(),b.ju&&b.ju()&&(a.shiftKey&&(b=this.H.Ka),(0,D.eV)(this.H,b.getId(),a.shiftKey)),(0,D.hi)(a),b=D.k):b=D.WR.o.Kh.call(this,a);return b};
D.x.qr=function(a){var b=(0,D.Ej)(this,a.target);(0,D.dV)(this,b);this.XO&&this.XO!=b&&(this.XO.fu(),this.XO=D.o);b&&(b instanceof D.$R&&this.XO!=b&&(this.XO=b,b.gu()),(!b.Aa||!b.Aa())&&(0,D.cV)(this,b,a.shiftKey))};D.x.wB=function(a){(a=(0,D.Ej)(this,a.target))&&a.Aa&&a.Aa()&&(0,D.cV)(this,a,D.p)};D.dV=function(a,b){b&&(b instanceof D.JR&&b.Ug())&&(0,D.eV)(a.H,b.getId(),D.p)};D.cV=function(a,b,c){b.ju&&b.ju()&&(0,D.eV)(a.H,b.getId(),c)};
D.WR.prototype.fm=function(a,b,c){a=this.H.q();if("dim"==a.hoverBehavior){b=b.Mc?b.Mc():[];a.highlightedCategories=c?b.slice():D.o;c=new D.zm(c?"categoryRollOver":"categoryRollOut",a.highlightedCategories);b=D.fV.MR(this.H.Ka);var d=(0,D.hp)(a.hoverBehaviorDelay);this.GB.Pd(c,b,d,"any"==a.highlightMatch)}};D.WR.prototype.Bu=function(){return this.H.q().touchResponse};
D.$R=(0,D.t)();D.z.l(D.$R,D.z,"DvtBaseTreeNode");D.NR=new D.Lo("#000000",2,5,5,45,0.5);
D.$R.prototype.Init=function(a,b){this.H=a;this.ee=b;var c=this.H.q().nodeDefaults;this.Xa=b.id||b.label;this.hk=b.color?b.color:"#000000";this.hD=b.label;this.wq="string"==typeof b.labelStyle?new D.G(b.labelStyle):b.labelStyle;this.as=b.pattern;this.EG=b.selectable;this.Kt=b.shortDesc?b.shortDesc:b.tooltip;this.no=b.value;this.tF=b.drilling?b.drilling:c.drilling;this.gD=b.S;this.WB=b.gHa;this.Tw=1;this.uX=D.o;this.KN=this.Ib=D.p};
D.$R.prototype.S0=function(a){if(a!=D.o)for(var b=0;b<a.length;b++)a[b].lg=this;this.ul=a};D.$R.prototype.zc=function(){return this.ul?this.ul:[]};D.fS=function(a){var b=[],c,d;if(!a.hf())return b;for(var e=0;e<a.ul.length;e++)d=a.ul[e],c=(0,D.fS)(d),b.push(d),b=b.concat(c);return b};D.hS=function(a){var b=a.lg;b&&(b.uX=a)};D.$R.prototype.PA=function(a){return!a||!this.lg?D.p:this.lg==a?D.k:this.lg.PA(a)};
D.cS=function(a,b,c){var d=[];if(0>c)return d;if(0==c)return[a];if(b.hf()){a=b.zc();for(var e=0;e<a.length;e++)b=a[e],d=d.concat((0,D.cS)(b,b,c-1))}return d};D.hV=function(a,b){if(a.getId()==b)return a;for(var c=D.o,d=a.zc(),e=d.length,c=D.o,f=0;f<e;f++)if(c=d[f],c=(0,D.hV)(c,b))return c;return D.o};D.x=D.$R.prototype;D.x.q=(0,D.v)("ee");D.x.Mc=function(){if(this.WB)return[];var a=this.q().categories;a||(a=(a=(a=this.lg)?a.Mc():D.o)?a.slice():[],a.push(this.getId()));return a};D.x.getId=(0,D.v)("Xa");
D.x.Tc=(0,D.v)("no");D.x.qb=(0,D.v)("hk");D.x.De=function(){var a=this.H.q().tooltip;return a?(0,D.ip)(this.H.j().ge(),a,this.vp()):this.Kt};D.x.vi=(0,D.v)("hk");D.x.Bc=(0,D.v)("Kt");D.x.vp=function(){return{id:this.getId(),label:this.Nc(),value:this.Tc(),color:this.qb()}};D.x.wa=function(){return this.q()._index};D.x.fa=(0,D.v)("Tw");D.x.B=function(a){this.Tw=a;this.G&&this.G.B(this.Tw)};D.x.yf=function(a){this.q()._expanded=a};D.x.Qa=function(){return this.q()._expanded!==D.p};
D.x.ju=function(){return"replace"==this.tF||"insertAndReplace"==this.tF};D.x.rd=function(){var a=this.H.q()._spb;if(!a||!a[this.gD])a=D.o;else{for(var a=a[this.gD],b=[],c=0;c<a.length;c++)b.push(new D.Gi(a[c].popupId,a[c].triggerType,a[c].alignId,a[c].align));a=b}return a};D.x.P=(0,D.t)();D.x.yy=function(a){var b=this.zc();if(b!=D.o)for(var c=0;c<b.length;c++)b[c].P(a)};D.x.Ad=function(){(0,D.hS)(this);return this};D.x.Ee=function(){return new D.A(0,0,0,0)};D.x.yj=(0,D.ca)(D.o);
D.x.Vd=function(){this.Ib=D.k;this.Ob();this.gu&&this.gu()};D.x.jc=function(){this.Ib&&(this.Ib=D.p,this.Db());this.fu&&this.fu()};D.x.pc=(0,D.v)("Ib");D.x.gu=function(){this.KN=D.k};D.x.fu=function(){this.KN=D.p};D.x.Aa=function(){return"off"!=this.EG&&this.H.t8!=D.o};D.x.Da=(0,D.v)("Ne");D.x.jb=function(a){this.Ne=a;this.$m()};D.x.Ob=(0,D.t)();D.x.Db=(0,D.t)();D.x.Ge=function(a,b){this.B(b)};D.x.zj=function(a){return this.H.YI(a)};D.x.yk=function(){return this.H.RB(this)};D.x.Zt=function(){return this.H.QB()};
D.x.iH=(0,D.ca)(D.o);D.x.uH=(0,D.ca)(D.o);D.x.contains=(0,D.ca)(D.p);D.x.AD=(0,D.ca)(D.o);D.x.Qm=function(){return[]};D.x.ur=(0,D.t)();D.x.gf=function(a,b){a.pO||(0,D.Tm)(a,b.zc(),this.zc());var c=this.Qm(),d=b.Qm(c),e;if(!D.H.Xc(d,c)&&(e=new D.qn(this.H.j(),this,this.H.nI),(0,D.T)(e.J,"typeNumberArray",this,this.Qm,this.ur,c),a.add(e,1),c=this.no!=b.no,e=D.I.oba(this.hk)!=D.I.oba(b.hk),this.ur(d),(d=this.H.q().animationUpdateColor)&&(c||e)))this.hk=d};
D.x.qg=function(a){if(!a.pO||!a.pO||!(a.sQ.getId()==this.getId()||(0,D.$U)(a.PX,this))){this.B(0);var b=new D.Vm(this.H.j(),this,this.H.nI);a.add(b,2);if(this.hf())for(b=0;b<this.ul.length;b++)this.ul[b].qg(a)}};D.x.kh=function(a,b){b.k(this.G);var c=new D.sn(this.H.j(),this,this.H.nI);a.add(c,0);if(!a.pO&&this.hf())for(c=0;c<this.ul.length;c++)this.ul[c].kh(a,b)};D.x.hf=function(){return this.ul!=D.o&&0<this.ul.length};D.dS=function(a){var b=0;for(a=a.lg;a;)b++,a=a.lg;return b};
D.$R.prototype.BI=function(){return this.as?new D.eh(this.as,this.hk):new D.En(this.hk)};D.mS=function(a,b){var c=a.as?"#000000":D.I.tj(a.hk);b.pa(c);var d=[];d.push(a.H.q().nodeDefaults.labelStyle);a.wq&&d.push(a.wq);b.Ha((0,D.Go)(d));D.Io===D.k&&b.pa(c)};D.bS=function(a){var b=11;(a=a.H.q().nodeDefaults.labelStyle.BA())&&(b=(0,window.parseFloat)(a));return b};D.$R.prototype.ia=(0,D.v)("G");D.$R.prototype.Nc=(0,D.v)("hD");D.aS=function(a){return a.H.cZ?a.H.cZ[a.gD]:D.o};D.$R.prototype.Eh=function(){return this.ju()};
D.$R.prototype.$m=(0,D.t)();
D.JR=function(a,b,c,d,e){this.Init(c,d,e);this.Pb=a;this.Xa=b;this.qO=D.p};D.z.l(D.JR,D.Fj,"DvtBaseTreePeer");D.x=D.JR.prototype;D.x.getId=(0,D.v)("Xa");D.x.Ug=(0,D.v)("qO");D.x.oda=(0,D.ba)("qO");D.x.gu=function(){this.Pb&&this.Pb.gu&&this.Pb.gu()};D.x.fu=function(){this.Pb&&this.Pb.fu&&this.Pb.fu()};
D.lV=(0,D.t)();D.z.l(D.lV,D.z,"DvtTreeBreadcrumbsRenderer");D.lV.cxa=6;D.lV.Vxa="color: #003286;";
D.lV.P=function(a,b,c,d){var e=a.j(),f=a.q().styleDefaults,g=[];g.push(new D.G(D.lV.Vxa));g.push(f._drillTextStyle);var g=(0,D.Go)(g).toString(),h=g+"text-decoration: underline;",j=[];j.push(f._currentTextStyle);f=(0,D.Go)(j).toString();e=new D.Wr(e,a.lza,a,{bw:g,jca:h,ica:h,tqa:f});a.k(e);c=c.slice(0).reverse();c.push({label:d});e.P({items:c},b.e);d=e.F();(0,D.pk)(e,b.x,b.y);d=d.g+D.lV.cxa;b.y+=d;b.g-=d;a.removeChild(e);return e};
D.FR=(0,D.t)();D.z.l(D.FR,D.z,"DvtTreeLegendRenderer");D.FR.$xa=4;D.FR.Nw=7;D.FR.QU=24;D.FR.Zxa=11;D.FR.wha="#636363";D.FR.POa="color:"+D.FR.wha+";";
D.FR.P=function(a,b,c){var d=a.q(),e=d.sizeLabel,f=d.colorLabel;if(!(e==D.o&&f==D.o&&c==D.o)){var g=a.j(),h=a.ka(),j=new D.D(g);a.k(j);var l=D.FR.RQ(g,a,j,b.e,e,f,c),m=(0,D.YH)(a.q().skin)?D.o:"#000000",n=[];n.push(d.styleDefaults._labelStyle);var m={borderColor:m,bw:(0,D.Go)(n)},d=D.jR.Vca(g,h,j,b.e,b.g,c,m),n=l?l.F():D.o,q=d?d.F():D.o;if(l&&!d)l.I(b.y+(b.e-n.e)/2);else if(d&&!l)d.I(b.y+(b.e-q.e)/2);else if(d&&l){var r=b.e-D.FR.QU;n.e+q.e>r&&(n.e>r/2&&q.e>r/2?(j.removeChild(l),j.removeChild(d),l=
D.FR.RQ(g,a,j,r/2,e,f,c),d=D.jR.Vca(g,h,j,r/2,b.g,c,m)):n.e>q.e?(h=r-q.e,j.removeChild(l),l=D.FR.RQ(g,a,j,h,e,f,c)):(e=r-n.e,j.removeChild(d),d=D.jR.Vca(g,h,j,e,b.g,c,m)),n=l.F(),q=d.F());(0,D.E)(g)?(d.I(b.x),l.I(b.x+b.e-n.e)):(l.I(b.x),d.I(b.x+b.e-q.e))}c=j.F();j.O(b.y+b.g-c.g);b.g-=c.g+D.FR.$xa;a.removeChild(j);return j}};
D.FR.RQ=function(a,b,c,d,e,f){var g=(0,D.E)(a),h=b.ka(),j=b.q().styleDefaults,l=D.o;if(e||f){l=new D.D(a);c.k(l);var m=[];m.push(j._attributeTypeTextStyle);c=(0,D.Go)(m);m=[];m.push(j._attributeValueTextStyle);var j=(0,D.Go)(m),n,q,r,s,m=0;e&&(n=(0,D.nk)(b.q(),"labelSize",b.ZZ(),"SIZE"),n=new D.Kf(a,n,0,0),n.Ha(c),l.k(n),r=n.Eb().e,q=new D.Kf(a,e,0,0),q.Ha(j),l.k(q),s=q.Eb().e,m=r+s+D.FR.Nw);var u,w,y,C,O=0;f&&(u=(0,D.nk)(b.q(),"labelColor",b.ZZ(),"COLOR"),u=new D.Kf(a,u,0,0),u.Ha(c),l.k(u),y=u.Eb().e,
w=new D.Kf(a,f,0,0),w.Ha(j),l.k(w),C=w.Eb().e,O=y+C+D.FR.Nw);d-=D.FR.QU;m+O>d&&(a=d/2,m>a&&O>a?(D.$e.Qb(q,a-r-D.FR.Nw,window.Infinity,l)?(s=q.Eb().e,h.Ca(q,new D.Fj(e))):(l.removeChild(n),l.removeChild(q),q=D.o,s=0),D.$e.Qb(w,a-y-D.FR.Nw,window.Infinity,l)?(C=w.Eb().e,h.Ca(w,new D.Fj(f))):(l.removeChild(u),l.removeChild(w),w=D.o,C=0)):m>O?D.$e.Qb(q,d-O-r-D.FR.Nw,window.Infinity,l)?(s=q.Eb().e,h.Ca(q,new D.Fj(e))):(l.removeChild(n),l.removeChild(q),q=D.o,s=0):D.$e.Qb(w,d-m-y-D.FR.Nw,window.Infinity,
l)?(C=w.Eb().e,h.Ca(w,new D.Fj(f))):(l.removeChild(u),l.removeChild(w),w=D.o,C=0));d=0;g?(w&&(w.ca(d),d+=C+D.FR.Nw,u.ca(d),d+=y+D.FR.QU),q&&(q.ca(d),d+=s+D.FR.Nw,n.ca(d))):(q&&(n.ca(d),d+=r+D.FR.Nw,q.ca(d),d+=s+D.FR.QU),w&&(u.ca(d),d+=y+D.FR.Nw,w.ca(d)))}return l};
D.gV=function(a){this.Init(a)};D.z.l(D.gV,D.jk,"DvtBaseTreeKeyboardHandler");D.gV.prototype.qy=function(a){return this.tg(a)&&!a.ctrlKey};D.gV.prototype.ar=function(a){return 32==a.keyCode&&a.ctrlKey};
D.VR=(0,D.t)();D.z.l(D.VR,D.Nj,"DvtBaseTreeDefaults");
D.aV={skin:"alta",animationDuration:500,animationOnDataChange:"none",animationOnDisplay:"none",highlightMatch:"all",hoverBehavior:"none",hoverBehaviorDelay:200,nodeDefaults:{labelStyle:new D.G("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 11px;")},selectionMode:"multiple",sorting:"off",_statusMessageStyle:new D.G("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;"),styleDefaults:{_attributeTypeTextStyle:new D.G("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;font-size:12px;font-weight:bold;color:#4F4F4F"),_attributeValueTextStyle:new D.G("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;font-size:12px;"),
_currentTextStyle:new D.G("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;font-size:12px;"),_drillTextStyle:new D.G("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;font-size:12px;"),_labelStyle:new D.G("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;")},touchResponse:"auto",_resources:{}};D.VR.prototype.Init=function(a){a={skyros:D.pl.bd(a.skyros,D.aV),alta:D.pl.bd(a.alta,{})};D.VR.o.Init.call(this,a)};
D.fV={};D.z.l(D.fV,D.z,"DvtBaseTreeUtils");D.fV.Upa=function(a,b){var c=b,d=a.zc();if(d)for(var e=0;e<d.length;e++)var f=D.fV.Upa(d[e],b+1),c=window.Math.max(c,f);return c};D.fV.Vpa=function(a){var b=1;if(a=a.zc())for(var c=0;c<a.length;c++)b+=D.fV.Vpa(a[c]);return b};D.fV.MR=function(a){var b=[];D.fV.WU(a,b);return b};D.fV.qIa=function(a){var b=[];D.fV.WU(a,b,D.p,D.k);return b};D.fV.tra=function(a){var b=[];D.fV.WU(a,b,D.k);return b};D.fV.kMa=function(a,b){return D.H.yM(a,b.categories)};
D.fV.lHa=function(a,b){var c=a.S;if(!(c==D.o||a.min!=D.o&&a.max!=D.o)){for(var d=window.Infinity,e=-window.Infinity,f=0;f<b.length;f++){var g=b[f];c==g.gD&&(g=g.q()._cv,g!=D.o&&(e=window.Math.max(e,g),d=window.Math.min(d,g)))}a.min==D.o&&(a.min=d);a.max==D.o&&(a.max=e)}};D.fV.lNa=function(a,b){for(var c=0;c<a.length;c++){var d=a[c],e=d.dHa,d=d.$Na;if(e instanceof D.hR&&d!=D.o)for(var f=0;f<b.length;f++){var g=b[f];if(d==g.gD){var h=e.get(g.q()._cv);h&&(g.hk=h)}}}};
D.fV.WU=function(a,b,c,d){if(a){var e=a.zc(),f=e?e.length:0;(!c||0==f)&&(!d||a.ia())&&b.push(a);for(a=0;a<f;a++)D.fV.WU(e[a],b,c,d)}};
D.mV=function(a){this.wpa=a;this.Ka=a.Ka};(0,D.da)("DvtTreeAutomation",D.mV);D.z.l(D.mV,D.Dj,"DvtTreeAutomation");D.mV.prototype.ql=function(a){var b=this.wpa.dba(a);if(!b)return a.getParent()instanceof D.Oe&&(a=a.getParent()),b=a.getParent(),b instanceof D.Wr?"breadcrumbs["+(0,D.Pt)(b,a)+"]":D.o;if(b instanceof D.$R){a="";if(!this.Ka.WB){if(b==this.Ka)return"node[0]";a+="[0]"}a=(b=this.vP(b,this.Ka.zc()))?a+b:a;if(0<a.length)return"node"+a}return D.o};
D.mV.prototype.vP=function(a,b){if(b&&0<b.length)for(var c=0;c<b.length;c++){if(b[c]==a)return"["+c+"]";var d=this.vP(a,b[c].zc());if(d)return"["+c+"]"+d}return D.o};
D.mV.prototype.If=function(a){return!a?D.o:"tooltip"==a?(0,D.bm)(this.wpa):0==a.indexOf("breadcrumbs")?(a=(0,D.St)(this.Ka.H.Faa(),a.substring(a.indexOf("[")+1,a.indexOf("]"))))?a.sa():D.o:!this.Ka.WB&&(a=a.substring(0,a.indexOf("["))+a.substring(a.indexOf("]")+1),"node"==a)?this.Ka.ia().sa():(a=(0,D.nV)(this,this.Ka,a))?a.ia().sa():D.o};D.mV.prototype.getDomElementForSubId=D.mV.prototype.If;
D.nV=function(a,b,c){var d=c.indexOf("["),e=c.indexOf("]");if(0<=d&&0<=e){d=c.substring(d+1,e);c=c.substring(e+1);var e=c.indexOf("["),f=c.indexOf("]");return(b=(0,D.oV)(b.zc(),d))&&0<=e&&0<=f?(0,D.nV)(a,b,c):b}};D.pV=function(a,b,c){var d=c.shift();b=(0,D.oV)(b.zc(),d);return 0==c.length?b:0<c.length?(0,D.pV)(a,b,c):D.o};
D.mV.prototype.Nb=function(a){!this.Ka.WB&&0==a[0]&&a.shift();a=0==a.length?this.Ka:(0,D.pV)(this,this.Ka,a);return{color:a.qb(),label:a.Nc(),selected:a.Da()==D.i?D.p:a.Da(),size:a.Tc(),tooltip:a.Bc()}};D.mV.prototype.getNode=D.mV.prototype.Nb;D.oV=function(a,b){for(var c=0;c<a.length;c++)if(b==a[c].wa())return a[c];return D.o};

  return D;
});