/**
 * Copyright (c) 2014, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(['./DvtToolkit', './DvtOverview'], function(dvt) {
  // Internal use only.  All APIs and functionality are subject to change at any time.
  
  // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  
D.LU=function(a,b,c){this.Init(a,b,c)};(0,D.da)("DvtTimelineOverview",D.LU);D.z.l(D.LU,D.xo,"DvtTimelineOverview");D.LU.prototype.Init=function(a,b,c){D.LU.o.Init.call(this,a,b,c);a=[D.I.BD(D.I.Fm("#aadd77",0.35)),"#aadd77",D.I.BD(D.I.wo("#aadd77",0.5))];D.bP.am()&&(a=["#aadd77"]);this.L5=a;this.yma=(0,D.ao)();this.st=12};D.LU.prototype.Nra=function(){return new D.MU(this)};
D.LU.prototype.Ku=function(a){D.LU.o.Ku.call(this,a);this.Gq=a.gT;this.nn=a.VMa;this.HY=a.HNa;this.M5=a.rqa;this.c6="#267DB3 #68C182 #FAD55C #ED6647 #8561C8 #6DDBDB #FFB54D #E371B2 #47BDEF #A2BF39 #A75DBA #F7F37B".split(" ");a.bw&&(this.wq=new D.G(a.bw));a="solid"==this.A("_","bs")?(0,window.parseInt)(this.A("_","bof"),10):1;var b="solid"==this.A("_as","bs")?(0,window.parseInt)(this.A("_as","bof"),10):1,c="solid"==this.A("_s","bs")?(0,window.parseInt)(this.A("_s","bof"),10):1;this.BX="none"!=this.Gq?
window.Math.max(b,c,a,1)/2+1:1;this.cP=this.Sa()?0:0.75;this.Ija=[this.cP,this.cP,this.cP];this.UEa=new D.fg(250,this.L5,this.Ija);this.CDa=new D.fg(180,this.L5,this.Ija);a=this.Sa()?0:1;this.yAa=new D.hg("#aadd77",a)};D.LU.prototype.kD=function(a,b,c,d,e,f){D.LU.o.kD.call(this,a,b,c,d,e,f,this.wq)};D.yU=function(a,b){for(var c="_mrk_"+b,d="_drn_"+b,e=a.Ja(),f=0;f<e;f++){var g=a.ha(f);if(g!=D.o&&(c==g.getId()||d==g.getId()))return g}return D.o};D.x=D.LU.prototype;D.x.mH=function(a){return a.getId().substr(5)};
D.x.A=function(a,b){return this.AAa[a+b]};D.x.ja=function(a){return a.Pb!=D.o?a.Pb.ja():a.ta().qc};D.x.na=function(a){return a.Pb!=D.o?a.Pb.na():a.ta().oc};D.x.vc=function(a){a=a.vc();a==D.o&&(a=this.Sa()?(this.Ga-this.zH()-4)/2:1);return a};D.x.Ac=function(a){a=a.Ac();a==D.o&&(a=1);return a};
D.x.Eca=function(a,b){D.LU.o.Eca.call(this,a,b);if(this.nn!=D.o){for(var c=(0,D.NU)(this,this.ob,this.Xb,a,b,this.st),d=[],e=0;e<this.nn.length;e++){var f=this.nn[e];if(f.Sh==D.o){var g=c,h="_mrk_"+f.getId(),j=f.qb(),l=f.N6,m=f.jba();m==D.o&&(m=this.cP,0==m&&j!=D.o&&(m=1));var n=this.vc(f),q=this.Ac(f),r=f.rb();if(this.Sa())var r="rectangle",n=2*n,g=2*q,q=f.na()+n/2,s=f.ja()+g/2;else n*=g,g*=q,q=f.ja()+n/2,s=f.na()+g/2;h=new D.dh(this.j(),r,D.o,q,s,n,g,D.o,h);h.Pb=f;j==D.o&&m==this.cP&&l==D.o?(l=
"circle"==r?this.UEa:this.CDa,j=this.yAa):(n=this.L5,j!=D.o&&(D.bP.am()?n=[j]:(n=D.I.Fm(j,0.5),g=D.I.wo(j,0.5),n=[n,j,g])),g=[m,m,m],l=l==D.o?"circle"==r?new D.fg(250,n,g):new D.fg(180,n,g):new D.En(j,g[0]),j=new D.hg(j,m));h.L(l);h.V(j);"none"!=this.Gq&&h.Lf(D.k);j=this.Ja();m=this.ha(j-1);j>this.xq&&("tb"==m.getId()||"arr"==m.getId())?this.Ma(h,j-this.xq):this.k(h);f.Qe(h);this.vn(h,"_");(this.Sa()||"rectangle"==r||"diamond"==r||"triangleUp"==r||"triangleDown"==r||"plus"==r)&&"false"!=this.M5.Ica&&
(0,D.Ei)(h)}else d[d.length]=f}this.F0(d);e=this.j();for(f=this.j8;0<f;f--)for(r=0;r<d.length;r++)j=d[r],f==j.nq&&(l=D.bP.fe(this.ob,this.Xb,j.getTime(),this.Sa()?this.Ta:this.Ga),h="_drn_"+j.getId(),m=9+5*j.nq,n=D.bP.fe(this.ob,this.Xb,j.Sh,this.Sa()?this.Ta:this.Ga),l=this.Sa()?this.nh()?new D.Te(e,0,l,m,n-l,h):new D.Te(e,this.Ga-m,l,m,n-l,h):this.nh()?new D.Te(e,this.Ga-n,this.Ta-m-20,n-l,m,h):new D.Te(e,l,this.Ta-m-20,n-l,m,h),l.L(new D.En(j.Cz)),h=new D.hg(this.A("_","dbc"),1,1),l.V(h),(0,D.Ei)(l),
l.Pb=j,this.k(l),j.NJ=l,j.BPa=m-2);this.removeChild(this.jpa);this.k(this.jpa);this.st=c}};D.x.F0=function(a){this.j8=0;var b=D.o;this.OJ==D.o&&(this.OJ={});for(var c=0;c<a.length;c++){var d=a[c],e=d.getId(),f=e.substring(e.indexOf(":")+1,e.length),f=f.substring(0,f.indexOf(":"));f!=b&&(this.fx=0,b=f);d.nq=(0,D.OU)(this,d,a);d.Cz==D.o&&(this.OJ[e]==D.o?(this.OJ[e]=this.fx,d.Cz=this.c6[this.fx],this.fx++,this.fx==this.c6.length&&(this.fx=0)):d.Cz=this.c6[this.OJ[e]])}};
D.x.mJa=function(){return this.OJ?this.OJ:D.o};D.LU.prototype.getDurationColorMap=D.LU.prototype.mJa;
D.NU=function(a,b,c,d,e,f){for(var g,h,j={max:1,X$:[]},l=a.Sa()?e:d,m=0;m<a.nn.length;m++){var n=a.nn[m];if(n.Sh!=D.o){var q=D.bP.fe(b,c,n.getTime(),l);(0,D.eP)(a)&&(q=l-q);n.ca(q)}else{var q=a,r=b,s=c,u=l,w=f/2,y=j,C=e,O=w*q.vc(n)+q.BX,M=w*q.Ac(n)+q.BX,r=D.bP.fe(r,s,n.getTime(),u);(0,D.eP)(q)&&(r=u-r-2*O);if(q.Sa())w=0,"solid"==q.A("_","bs")&&(w=(0,window.parseInt)(q.A("_","bw"),10)),u=q.nh()?w+4:q.Ga-2*q.vc(n)-w-4;else for(var u=3,J=0,s=0;1>s;){g=q;h=y;var R=n.rb(),N=r,Y=u,ha=O,ta=M,xa=w,Ea=C;"above"==
g.$X&&(Y+=(0,D.oP)(g));for(var ob=0;ob<h.X$.length;ob++){var La=h.X$[ob],kb=La.ja(),Dc=La.na(),Rb=La.rb(),Zd=g.vc(La),La=g.Ac(La),kb=window.Math.abs(N-kb),we=xa*Zd+g.BX+ha;if(!(kb>=we)&&(Rb="circle"==R&&"circle"==Rb&&ha==ta&&Zd==La?window.Math.sqrt(we*we-kb*kb):xa*La+g.BX+ta,Rb>window.Math.abs(Y-Dc)&&(Y=Dc+Rb,J=window.Math.max(J,Y+Rb),1<=xa&&Ea!=D.i&&J>Ea)))break}g=Y;h=J;g==u&&(s=1);J=h;u=g;s++}n.ca(r);n.va(u);y.X$.push(n);J>y.max&&(y.max=J);if(j.max>e)break}}return j.max>e&&1<f?(0,D.NU)(a,b,c,d,
e,f-1):f};D.OU=function(a,b,c){var d=c.length,e=b.getTime(),f=b.nq;f==D.o&&(f=1);for(var g=0;g<d;g++){var h=c[g];if(h!=b){var j=h.Sh;if(j!=D.o){var l=h.getTime(),h=h.nq;h==D.o&&(h=1);e>=l&&(e<=j&&f==h)&&(f=h+1,b.nq=f,f=(0,D.OU)(a,b,c))}}}f>a.j8&&(a.j8=f);return f};
D.LU.prototype.fU=function(a){var b=D.LU.o.fU.call(this,a);if(b!=D.o){if(b.Pb!=D.o){var c=b.Pb.JJ;c!=D.o&&this.j().ge().dN(a.pageX,a.pageY,c,"#000000");this.FH()&&this.setCursor("pointer")}if("none"!=this.Gq){a=D.p;if(this.sk!=D.o)for(c=0;c<this.sk.length;c++)if(b==this.sk[c]){a=D.k;break}a||(a=this.mH(b),c=new D.PU("highlight"),(0,D.El)(c,"itemId",a),this.dispatchEvent(c),(0,D.QU)(this,b))}}};
D.LU.prototype.eU=function(a){a=D.LU.o.eU.call(this,a);if(a!=D.o&&!(0,D.BP)(a)){this.j().ge().Cc();var b=D.p;if(this.sk!=D.o)for(var c=0;c<this.sk.length;c++)if(a==this.sk[c]){b=D.k;break}b||(b=this.mH(a),c=new D.PU("unhighlight"),(0,D.El)(c,"itemId",b),this.dispatchEvent(c),(0,D.RU)(this,a))}};
D.LU.prototype.uE=function(a,b,c){b=D.LU.o.uE.call(this,a,b,c);if(b!=D.o&&(a=a.ctrlKey||a.shiftKey||(0,D.Jf)(),"none"!=this.Gq)){c=this.mH(b);var d=new D.PU("selection");(0,D.El)(d,"itemId",c);(0,D.El)(d,"multiSelect",a);this.dispatchEvent(d);a=b.Pb.getTime();a!=D.o&&(c=new D.PU("scrollTime"),c.setTime(a),this.dispatchEvent(c),a=this.ha(1),b=this.Sa()?this.ja(b)-a.getHeight()/2:this.ja(b)-a.getWidth()/2,(0,D.qP)(this,b))}};
D.QU=function(a,b){if(a.sk!=D.o)for(var c=0;c<a.sk.length;c++)if(b==a.sk[c])return;a.vn(b,"_h")};D.RU=function(a,b){if(a.sk!=D.o)for(var c=0;c<a.sk.length;c++)if(b==a.sk[c])return;a.vn(b,"_")};D.zU=function(a,b){a.sk==D.o&&(a.sk=[]);var c=D.o;0<a.sk.length&&(c=a.sk[a.sk.length-1]);a.sk.push(b);c!=D.o&&a.vn(c,"_s");a.vn(b,"_as")};
D.LU.prototype.vn=function(a,b){if(a instanceof D.dh){var c=D.p,d=D.p;if("solid"==this.A(b,"bs")){var c=D.k,e=this.A(b,"bc");e==D.o&&(e="#000000");var f=this.A(b,"gc");f!=D.o&&"none"!=f&&(d=D.k)}var g=a.Gia,h=a.L6;!c&&g!=D.o?(this.removeChild(g),a.Gia=D.o,h!=D.o&&(this.removeChild(h),a.L6=D.o)):!d&&h!=D.o&&(this.removeChild(h),a.L6=D.o);var j=a.Pa();if(c){var c=(0,window.parseInt)(this.A(b,"bw"),10),l=(0,window.parseInt)(this.A(b,"bof"),10);if(g==D.o){if("circle"==j){this.FH()&&(l=0);var m=(a.F().e+
2*l)*a.vc(),n=(a.F().g+2*l)*a.Ac(),q=this.ja(a)-l+m/2,r=this.na(a)-l+n/2}else this.Sa()?(m=(a.F().e+(c+1))*a.vc(),n=(a.F().g+(c+1))*a.Ac(),q=this.na(a)-(c+1)/2+m/2,r=this.ja(a)-(c+1)/2+n/2):(m=(a.F().e+2*l)*a.vc(),n=(a.F().g+2*l)*a.Ac(),q=this.ja(a)-l+m/2,r=this.na(a)-l+n/2);g=new D.dh(this.j(),j,D.o,q,r,m,n,D.o,a.getId()+"_border");this.Ma(g,this.Qf(a));a.Gia=g;g.L(this.yma)}e=new D.hg(e,this.A(b,"bo"),c);g.V(e);(this.Sa()||"rectangle"==j||"diamond"==j||"triangleUp"==j||"triangleDown"==j||"plus"==
j)&&"false"!=this.M5.Ica&&(0,D.Ei)(g);d&&(h==D.o&&(h=l-c,"circle"==j?(this.FH()&&(h=0),m=(a.F().e+2*h)*a.vc(),n=(a.F().g+2*h)*a.Ac(),q=this.ja(a)-h+m/2,r=this.na(a)-h+n/2):this.Sa()?(m=(a.F().e+3)*a.vc(),n=(a.F().g+3)*a.Ac(),q=this.na(a)+m/2,r=this.ja(a)-1+n/2):(m=(a.F().e+2*h)*a.vc(),n=(a.F().g+2*h)*a.Ac(),q=this.ja(a)-h+m/2,r=this.na(a)-h+n/2),h=new D.dh(this.j(),j,D.o,q,r,m,n,D.o,a.getId()+"_glow"),this.Ma(h,this.Qf(g)),a.L6=h,h.L(this.yma)),f=new D.hg(f,this.A(b,"go"),4),h.V(f),(this.Sa()||"rectangle"==
j||"diamond"==j||"triangleUp"==j||"triangleDown"==j||"plus"==j)&&"false"!=this.M5.Ica&&(0,D.Ei)(h))}}else if((j=a.getId())&&"_drn_"==j.substring(0,5))j=this.A(b,"dbc"),j==D.o&&(j="#000000"),f=(0,window.parseInt)(this.A(b,"dbw"),10),a.V(new D.hg(j,1,f))};D.LU.prototype.Gf=function(){this.cha||(this.cha=new D.SU(this));return this.cha};D.LU.prototype.getAutomation=D.LU.prototype.Gf;
D.MU=function(a){this.Init(a)};D.z.l(D.MU,D.z,"DvtTimelineOverviewParser");D.x=D.MU.prototype;D.x.Init=function(a){this.H=a;this.vv=new D.lj};D.x.parse=function(a){var b=this.vv.parse(a);a=this.DE(b);var b=b.zc(),c;if(c=b[0]){var d={};d.width=c.v("width");d.height=c.v("height");d.cOa=c.zc();c=d}else c=D.o;a.Zta=c;a.VMa=this.X8(b[1],a.rqa);2<b.length&&(a.oIa=!b[2]?D.o:b[2].zc());return a};
D.x.DE=function(a){var b={};b.start=(0,window.parseInt)(a.v("start"));b.end=(0,window.parseInt)(a.v("end"));b.width=(0,window.parseInt)(a.v("width"));b.Zca=(0,window.parseInt)(a.v("renstart"));b.currentTime=(0,window.parseInt)(a.v("ocd"));b.orientation=a.v("orn");b.sta=a.v("ovp");b.gT=a.v("selmode");b.dca=a.v("rtl");b.borderTopStyle=a.v("_bts");b.borderTopColor=a.v("_btc");b.HNa=a.v("sid");b.Npa=a.v("_aoc");var c={};c.shape=a.v("_ds");c.$H=a.v("_dsx");c.aI=a.v("_dsy");c.opacity=a.v("_do");c.color=
a.v("_fc");c.Ica=a.v("_ph");b.rqa=c;b.Mba=a.v("_hfc");b.Oba=a.v("_htc");b.csa=a.v("_hbi");b.osa=a.v("_hw");b.lsa=a.v("_hh");b.Bda=a.v("_wbc");b.Jda=a.v("_wbts");b.Hda=a.v("_wbrs");b.Dda=a.v("_wbbs");b.Fda=a.v("_wbls");b.Ida=a.v("_wbtc");b.Gda=a.v("_wbrc");b.Cda=a.v("_wbbc");b.Eda=a.v("_wblc");b.Cca=a.v("_obc");b.iaa=a.v("_ctic");b.uda=a.v("_tic");b.Xta=a.v("_tabc");b.Yta=a.v("_tabo");b.bw=a.v("_ls");c={};c._bs=a.v("_bs");c._bc=a.v("_bc");c._bw=a.v("_bw");c._bof=a.v("_bof");c._bo=a.v("_bo");c._gc=
a.v("_gc");c._go=a.v("_go");c._dbs=a.v("_dbs");c._dbc=a.v("_dbc");c._dbw=a.v("_dbw");c._hbs=a.v("_hbs");c._hbc=a.v("_hbc");c._hbw=a.v("_hbw");c._hbof=a.v("_hbof");c._hbo=a.v("_hbo");c._hgc=a.v("_hgc");c._hgo=a.v("_hgo");c._hdbs=a.v("_hdbs");c._hdbc=a.v("_hdbc");c._hdbw=a.v("_hdbw");c._sbs=a.v("_sbs");c._sbc=a.v("_sbc");c._sbw=a.v("_sbw");c._sbof=a.v("_sbof");c._sbo=a.v("_sbo");c._sgc=a.v("_sgc");c._sgo=a.v("_sgo");c._sdbs=a.v("_sdbs");c._sdbc=a.v("_sdbc");c._sdbw=a.v("_sdbw");c._asbs=a.v("_asbs");
c._asbc=a.v("_asbc");c._asbw=a.v("_asbw");c._asbof=a.v("_asbof");c._asbo=a.v("_asbo");c._asgc=a.v("_asgc");c._asgo=a.v("_asgo");c._asdbs=a.v("_asdbs");c._asdbc=a.v("_asdbc");c._asdbw=a.v("_asdbw");b.jHa=c;return b};D.x.X8=function(a,b){if(!a)return D.o;for(var c=[],d=a.zc(),e=0;e<d.length;e++){var f=this.W2(d[e],b),f=new D.TU(this.H,f);c.push(f)}return c};
D.x.W2=function(a,b){var c={},d="true"==a.v("_sd");c.id=a.v("tid");c.bda=a.v("rk");c.time=a.v("t");c.nD=a.v("et");c.shape=a.v("s");d&&c.shape==D.o&&(c.shape=b.shape);c.KZ=a.v("d");c.color=a.v("c");c.OZ=a.v("dfc");d&&c.color==D.o&&(c.color=b.color);c.$H=a.v("sx");d&&c.$H==D.o&&(c.$H=b.$H);c.aI=a.v("sy");d&&c.aI==D.o&&(c.aI=b.aI);c.nLa=a.v("g");c.opacity=a.v("o");d&&c.opacity==D.o&&(c.opacity=b.opacity);return c};
D.TU=function(a,b){this.Init(a,b)};D.z.l(D.TU,D.z,"DvtTimelineOverviewNode");D.x=D.TU.prototype;
D.x.Init=function(a,b){this.H=a;this.XQ=b.bda;this.Xa=b.id;this.wGa=(0,window.parseInt)(b.time);this.Sh=b.nD==D.o?D.o:(0,window.parseInt)(b.nD);this.G="circle";"square"==b.shape?this.G="rectangle":"plus"==b.shape?this.G="plus":"diamond"==b.shape?this.G="diamond":"triangleUp"==b.shape?this.G="triangleUp":"triangleDown"==b.shape&&(this.G="triangleDown");this.JJ=b.KZ;this.hk=b.color;this.N6=b.nLa;b.opacity!=D.o&&(this.sEa=(0,window.parseFloat)(b.opacity));b.$H!=D.o&&(this.bGa=(0,window.parseFloat)(b.$H));
b.aI!=D.o&&(this.cGa=(0,window.parseFloat)(b.aI));b.OZ!=D.o&&(this.Cz=b.OZ)};D.x.getId=(0,D.v)("Xa");D.x.rba=(0,D.v)("XQ");D.x.getTime=(0,D.v)("wGa");D.x.vc=(0,D.v)("bGa");D.x.Ac=(0,D.v)("cGa");D.x.qb=(0,D.v)("hk");D.x.rb=(0,D.v)("G");D.x.jba=(0,D.v)("sEa");D.x.ia=(0,D.v)("vg");D.x.Qe=(0,D.ba)("vg");D.x.ja=(0,D.v)("Ab");D.x.ca=(0,D.ba)("Ab");D.x.na=(0,D.v)("Ub");D.x.va=(0,D.ba)("Ub");
D.PU=function(a){this.Init("timeline");this.Am=a};D.z.l(D.PU,D.EP,"DvtTimelineOverviewEvent");D.PU.prototype.mH=function(){return this.Yi("itemId")};
D.SU=function(a){this.cc(a)};D.z.l(D.SU,D.Dj,"DvtTimelineOverviewAutomation");D.SU.prototype.cc=(0,D.ba)("lc");
D.SU.prototype.ql=function(a){var b=a.getId();if(a instanceof D.dh){a=b.split(":");if(4!=a.length)return D.o;b=this.lc.HY==D.o?D.o:this.lc.HY.split(" ");if(b!=D.o&&(b=D.H.wa(b,a[1]),-1<b))return"marker["+b+"]["+a[2]+"]"}else{if("window"==b)return"range_window";if("lh"==b||"lhb"==b||"lbgrh"==b)return"range_start_handle";if("rh"==b||"rhb"==b||"rbgrh"==b)return"range_end_handle";if("grpy"==b)return a=a.getParent().RR(a),this.ql(a)}return D.o};
D.SU.prototype.If=function(a){for(var b=a.split("["),c=b.length,d=1;d<c;d++){var e=b[d],e=e.substr(0,e.length-1),f=(0,window.parseFloat)(e),e=(0,window.isNaN)(f)?e:f;b[d]=e}if(b&&3==b.length&&"marker"==b[0]){if(c=this.lc.HY==D.o?D.o:this.lc.HY.split(" "),c!=D.o&&(d=(0,window.parseInt)(b[1],10),-1<d&&d<c.length)){a:{a=this.lc.nn;b="tl1:"+c[d]+":"+b[2]+":";for(c=0;c<a.length;c++)if(d=a[c],e=d.getId(),e!=D.o&&0==e.indexOf(b)){b=d;break a}b=D.o}return b?b.ia().sa():D.o}}else{if("range_window"==a)return this.lc.ha(1).sa();
if("range_start_handle"==a)return this.lc.ha(this.lc.Ja()-this.lc.xq).sa();if("range_end_handle"==a)return(0,D.yP)(this.lc).sa()}return D.o};(0,D.da)("DvtTimelineOverviewAutomation.prototype.getDomElementForSubId",D.SU.prototype.If);

  return D;
});