/**
 * Copyright (c) 2014, Oracle and/or its affiliates.
 * All rights reserved.
 */
"use strict";
define(['./DvtToolkit', './DvtBaseTreeView'], function(dvt) {
  // Internal use only.  All APIs and functionality are subject to change at any time.
  
  // Map the D namespace to dvt, which is used to provide access across partitions.
  var D = dvt;
  
D.wV=function(a,b,c){this.Init(a,b,c)};(0,D.da)("DvtTreemap",D.wV);D.z.l(D.wV,D.BR,"DvtTreemap");D.wV.newInstance=function(a,b,c){return new D.wV(a,b,c)};D.x=D.wV.prototype;D.x.Init=function(a,b,c){D.wV.o.Init.call(this,a,b,c);this.rf=new D.xV;this.setId("treemap1000"+window.Math.floor(1E9*window.Math.random()))};
D.x.hN=function(a){D.wV.o.hN.call(this,a);a=this.q();this.nf="sliceAndDiceHorizontal"==a.layout?new D.sV(D.k):"sliceAndDiceVertical"==a.layout?new D.sV(D.p):new D.tV;this.hd=[];var b=a.isolatedNode;if(b&&this.Ka){var c=(0,D.fS)(this.Ka);c.push(this.Ka);for(var d=0;d<c.length;d++)if(c[d].getId()==b){this.hd.push(c[d]);break}}"auto"==a.animationOnDisplay&&(a.animationOnDisplay="alphaFade")};
D.x.bq=function(a){var b="jet"!=this.q()._environment?7:1,b=window.Math.max(window.Math.ceil(b*window.Math.min(a.e,a.g)/400),1);a.x+=b;a.y+=b;a.e-=2*b;a.g-=2*b;b=this.nf.Vaa(this,1);a.x+=b;a.e-=2*b;(0,D.ER)(this,a);this.wb=D.FR.P(this,a,this.wX);a.x-=b;a.e+=2*b;b=this.hd.length;if(0<b&&this.pX)this.nf.cr(this,this.hd[b-1],a.x,a.y,a.e,a.g,D.k);else{this.Ka&&this.nf.cr(this,this.Ka,a.x,a.y,a.e,a.g,D.p);for(var c=0;c<b;c++)this.nf.cr(this,this.hd[c],a.x,a.y,a.e,a.g,D.k)}};
D.x.Ij=function(a){(0,D.HR)(this,a);this.bn&&a.k(this.bn);this.wb&&(a.k(this.wb),this.wb=D.o);if((0,D.IR)(this)){this.O6=new D.D(this.j());a.k(this.O6);this.sDa?this.sDa.P(a):this.Ka.hf()?(this.Ka.yy(a),(0,D.KR)(this,this.Ka)):this.Ka.P(a);this.B7=new D.D(this.j());a.k(this.B7);this.Px=new D.D(this.j());a.k(this.Px);a.k(this.O6);this.zC=new D.po(this.j(),[]);this.zC.kb(D.p);this.zC.qa(D.p);(0,D.Ei)(this.zC);a.k(this.zC);for(a=0;a<this.hd.length;a++){var b=this.hd[a].ia();this.B7.k(b)}}else(0,D.LR)(this,
a)};D.x.sr=function(){this.i1||(this.X.Cj(),this.bq(new D.A(0,0,this.Ga,this.Ta)),this.Ij(this.X),this.m3());D.wV.o.sr.call(this)};D.x.m3=function(){for(var a=this.Hb?this.Hb.getSelection():[],b=0;b<a.length;b++)if(0<this.hd.length){var c=this.hd[this.hd.length-1];(a[b]==c||a[b].PA(c))&&a[b].jb(D.k)}else a[b].jb(D.k)};D.x.xw=function(a){return new D.yV(a)};D.x.uI=function(a,b,c,d){return new D.zV(a,b,c,d)};
D.x.Tea=function(a){var b=(0,D.AV)(this);return b?(0,D.BV)(this,D.fV.tra(b)):a?(0,D.BV)(this,D.fV.tra(a)):D.o};D.x.TU=function(a){for(var b=0,c=this.Px.Ja(),d=0;d<c;d++){var e=this.Px.ha(d);a.zIndex>e.zIndex&&(b=d+1)}b<c?this.Px.Ma(a,b):this.Px.k(a)};D.x.LE=function(a,b){return 0<this.hd.length?this.hd[this.hd.length-1].AD(a,b):this.Ka.AD(a,b)};D.AV=function(a){return a.hd&&0<a.hd.length?a.hd[a.hd.length-1]:D.o};
D.DV=function(a,b){if("none"!=a.q().animationOnDataChange){for(var c=a.Hb?a.Hb.getSelection():[],d=0;d<c.length;d++)c[d].jb(D.p);for(var c=[(0,D.CV)(b)],d=(0,D.fS)(b),e=0;e<d.length;e++)c.push((0,D.CV)(d[e]));a.mr=new D.on(a.j(),c);a.mr.ie(a.sr,a);a.eb.gi(a);a.mr.play()}else a.P(D.o,a.Ga,a.Ta,D.k)};D.BV=function(a,b){var c=a.eb.Sf;return c?c.tD(b):b&&0<b.length?b[0]:D.o};D.wV.prototype.Hj=function(){return(0,D.nk)(this.q(),"componentName","DvtUtilBundle","TREEMAP")};D.wV.prototype.ZZ=(0,D.ca)("DvtTreemapBundle");
D.wV.prototype.Xp=function(a){return new D.EV(this,a)};
D.EV=function(a,b){this.Init(a,b);var c=this.H.q(),d=c.nodeDefaults,e=d.header,f=b.header?b.header:{};this.CCa=b.groupLabelDisplay?b.groupLabelDisplay:d.groupLabelDisplay;this.Sr=b.labelDisplay?b.labelDisplay:d.labelDisplay;this.sK=b.labelHalign?b.labelHalign:d.labelHalign;this.H7=b.labelValign?b.labelValign:d.labelValign;this.XCa=f.labelHalign?f.labelHalign:e.labelHalign;this.gla=f.labelStyle?new D.G(f.labelStyle):D.o;this.qV="on"==(f.useNodeColor?f.useNodeColor:e.useNodeColor);this.A7=f.isolate?
f.isolate:e.isolate;"auto"==this.A7&&(this.A7=(0,D.Jf)()?"off":"on");this.Pu=c.isolatedNode!=D.o&&c.isolatedNode==this.getId()};D.z.l(D.EV,D.$R,"DvtTreemapNode");D.x=D.EV.prototype;
D.x.P=function(a){if(this.hv){this.G=this.A5();a.k(this.G);var b;this.hf()?(this.PV=new D.D(this.H.j()),this.G.k(this.PV),this.yy(this.PV)):b=(0,D.aS)(this);if(b){var c=this.q()._cf,d=this.H.Fc;d.Ir=c;var c=this.Ba-8-2,e=this.Fa-4-2;0<c&&0<e&&((0,D.ng)(d,c),(0,D.og)(d,e),d.Ie((0,D.bS)(this)),this.o5=b=D.ze.XH(d,b,this.G),(0,D.E)(a.j())?(a=b.F(),a=this.Ab+this.Ba-4-1-a.e):a=this.Ab+4+1,(0,D.pk)(b,a,this.Ub+2+1))}else this.Kb=this.WO(this.G),this.Kb!=D.o&&(this.as&&"header"!=this.Wk)&&(a=this.Kb.Eb(),
this.ds=new D.Te(this.H.j(),a.x,a.y,a.e,a.g),this.ds.pa("#FFFFFF"),this.ds.qa(D.p),this.G.k(this.ds),a=this.Kb,"node"==this.Wk&&this.hf()?this.H.O6.k(a):this.G.k(a));this.hf()?this.G.Ud("group"):this.G.Ud("img");this.$m()}};
D.x.jb=function(a){D.EV.o.jb.call(this,a);if(this.G){a=this.H.q().nodeDefaults;var b=a.header;if(this.Da()){var c=this.Ab,d=this.Ub+1,e=this.Ba-1,f=this.Fa-1;(0,D.ij)()&&(d-=1);(0,D.HV)(this,this.$h);(0,D.HV)(this,this.Qx);this.Qx=this.$h=D.o;this.$h=new D.Te(this.H.j(),c,d,e,f);this.$h.qa(D.p);this.$h.L(D.o);(0,D.Ei)(this.$h);this.G.k(this.$h);this.Qx=new D.Te(this.H.j(),c+1,d+1,e-2,f-2);this.Qx.qa(D.p);this.Qx.L(D.o);(0,D.Ei)(this.Qx);this.G.k(this.Qx);"header"==this.Wk?(this.KN||this.pc()?this.sq.pa(b.hoverBackgroundColor):
(this.sq.pa(b.selectedBackgroundColor),this.Kb&&(0,D.IV)(this,this.Kb,"_selectedLabelStyle")),this.$h.Ra(b.selectedOuterColor),this.Qx.Ra(b.selectedInnerColor),(0,D.Jf)()&&(this.ze=(0,D.JV)(this,this.G))):(this.$h.Ra(a.selectedOuterColor),this.Qx.Ra(a.selectedInnerColor),!(0,D.Bq)()&&!(0,D.jj)()&&(0,D.Oo)(this.G,D.NR),this.H.TU(this.G))}else(0,D.HV)(this,this.Qx),this.Qx=D.o,(0,D.Jf)()&&(0,D.KV)(this),"header"==this.Wk?(this.KN||this.pc()?this.sq.pa(b.hoverBackgroundColor):((0,D.LV)(this,this.G,this.sq),
this.Kb&&(this.ju()?(0,D.IV)(this,this.Kb,"_drillableLabelStyle"):(0,D.IV)(this,this.Kb,"labelStyle"))),this.$h&&(this.KN||this.pc()?this.$h.Ra(b.hoverOuterColor):((0,D.HV)(this,this.$h),this.$h=D.o))):((0,D.Wz)(this.G),this.$h&&((0,D.HV)(this,this.$h),this.$h=D.o),(a=this.lg)&&a.PV&&a.PV.k(this.G))}};
D.x.Ob=function(){if(this.G&&this.hv){var a=this.H.q().nodeDefaults,b=a.header,c=(0,D.AV)(this.H);if(!(c!=D.o&&c!=this&&!this.PA(c))){var c=[],d,e,f,g;"header"==this.Wk?(this.sq.pa(b.hoverBackgroundColor),this.$h||(a=this.Ab,d=this.Ub+1,e=this.Ba-1,f=this.Fa-1,(0,D.ij)()&&(d-=1),this.$h=new D.Te(this.H.j(),a,d,e,f),this.$h.qa(D.p),this.$h.L(D.o),(0,D.Ei)(this.$h),this.G.k(this.$h)),this.$h.Ra(this.Da()?b.selectedOuterColor:b.hoverOuterColor),d=this.Ab+1.5+1,f=this.Ab+this.Ba-1.5-1,e=this.Ub+this.ip,
g=this.Ub+this.Fa-1.5-1,c.push(f,e,f,g,d,g,d,e),a=new D.hg(b.hoverInnerColor,0.8,3),this.Kb&&(this.ju()?(0,D.IV)(this,this.Kb,"_drillableHoverLabelStyle"):(0,D.IV)(this,this.Kb,"_hoverLabelStyle"))):(d=this.Ab+1,f=this.Ab+this.Ba-1,e=this.Ub+1,g=this.Ub+this.Fa-1,c.push(this.Ab,e,f,e,f,g,d,g,d,e),a=new D.hg(a.hoverColor,1,2));b=this.H;b.zC.wc(c);b.zC.V(a);b.zC.kb(D.k)}}};
D.x.Db=function(){if(this.G&&this.hv){var a=this.H.q().nodeDefaults.header;"header"==this.Wk&&(this.Da()?(this.sq.pa(a.selectedBackgroundColor),this.$h.Ra(a.selectedOuterColor),this.Kb&&(this.ju()?(0,D.IV)(this,this.Kb,"_drillableSelectedLabelStyle"):(0,D.IV)(this,this.Kb,"_selectedLabelStyle"))):((0,D.LV)(this,this.G,this.sq),this.$h&&(this.G.removeChild(this.$h),this.$h=D.o),this.Kb&&(this.ju()?(0,D.IV)(this,this.Kb,"_drillableLabelStyle"):(0,D.IV)(this,this.Kb,"labelStyle"))));this.H.zC.kb(D.p)}};
D.x.Ge=function(a,b){this.hf()?(this.Kb&&this.Kb.B(b),"header"==this.Wk&&(this.qV&&this.sq)&&this.sq.B(b)):D.EV.o.Ge.call(this,a,b)};D.x.oy=function(){return"off"!=this.A7&&"header"==this.Wk};D.x.uH=function(a){return!a||!a.XL()?D.EV.o.uH.call(this,a):new D.A(this.Ab,this.Ub,this.Ba,this.Fa)};
D.x.Ad=function(a){var b;if(a.type==D.kk)return D.EV.o.Ad.call(this,a);b=a.keyCode;if(32==b&&a.ctrlKey)return this;if(38==b&&a.altKey||221==b)(b=this.lg)&&b.getId()!=this.H.Ka.getId()?(a=b,(0,D.hS)(b)):a=this;else if(40==b&&a.altKey||219==b)a=(a=this.uX)?a:this.hf()?(0,D.BV)(this.H,this.zc()):this;else{var c=(0,D.AV)(this.H),d=0;if(c)if(this==c)d=0;else{b=this.lg;for(d=1;c!=b;)d++,b=b.lg}else{for(c=this;c.lg;)c=c.lg;d=(0,D.dS)(this)}b=(0,D.cS)(this,c,d);a=(0,D.lk)(this,a,b)}(0,D.hS)(a);return a};
D.x.Ee=function(){return new D.A(this.Ab,this.Ub,this.Ba,this.Fa)};D.x.yj=function(){return this.G?this.G.sa():D.o};
D.x.qT=function(a,b,c,d){if(!(0>=c||0>=d)){this.hv=D.k;this.ona=this.Qm();this.Ab=a;this.Ub=b;this.Ba=c?c:0;this.Fa=d?d:0;this.Wk=this.hf()?this.CCa:this.Sr;this.hD||(this.Wk="off");if("header"==this.Wk){this.ip=15;a=new D.Kf(this.H.j(),this.hD);a.Ie((0,D.bS)(this));(0,D.IV)(this,a,"labelStyle");a=D.$e.Dh(a).g;this.ip=window.Math.max(this.ip,a);this.oy()&&(this.ip=window.Math.max(this.ip,15));a=this.Ab;b=this.Ub+this.ip;c=this.Ba;d=this.Fa-this.ip;if(0<=c&&0<=d)return new D.A(a,b,c,d);this.Wk=D.o}return new D.A(this.Ab,
this.Ub,this.Ba,this.Fa)}};D.x.AD=function(a,b){if(this.contains(a,b)||!this.hv){for(var c=this.zc(),d=0;d<c.length;d++)if(c[d].contains(a,b))return c[d].AD(a,b);if(this.hv)return this}return D.o};D.x.contains=function(a,b){return a>=this.Ab&&a<=this.Ab+this.Ba&&b>=this.Ub&&b<=this.Ub+this.Fa};D.x.Qm=function(){var a=D.I.te(this.hk),b=D.I.pe(this.hk),c=D.I.oe(this.hk);return[this.Ab,this.Ub,this.Ba,this.Fa,a,b,c,this.hf()?0:window.Math.random()]};
D.x.ur=function(a){this.qT(a[0],a[1],a[2],a[3]);this.hk=D.I.$A(window.Math.round(a[4]),window.Math.round(a[5]),window.Math.round(a[6]));this.G&&((0,D.iI)(this.G,this.Ab,this.Ub,this.Ba,this.Fa),this.sq&&(0,D.iI)(this.sq,this.Ab+1,this.Ub+1,this.Ba-2,this.Fa-2),("header"!=this.Wk||this.qV)&&this.G.L(this.BI()),this.Da()&&this.jb(D.p),(0,D.HV)(this,this.Ez),(0,D.HV)(this,this.pR),this.pR=this.Ez=D.o,(0,D.KV)(this),(0,D.aS)(this)?((0,D.HV)(this,this.o5),this.o5=D.o):((0,D.HV)(this,this.ds),this.ds=D.o,
this.Kb&&this.Kb.getParent().removeChild(this.Kb),this.Kb=this.WO(this.G)))};D.CV=function(a){if(a.ona){var b=new D.qn(a.H.j(),a,0.3);(0,D.T)(b.J,"typeNumberArray",a,a.Qm,a.ur,a.Qm());a.ur(a.ona);return b}return D.o};D.EV.prototype.gf=function(a,b){return 0==(0,D.dS)(this)||b.hv&&0<b.Ba&&0<b.Fa?D.EV.o.gf.call(this,a,b):this.qg(a)};
D.EV.prototype.A5=function(){var a=this.H.j(),b;if("header"==this.Wk)b=new D.Te(a,this.Ab,this.Ub,this.Ba,this.Fa),this.sq=new D.Te(a,this.Ab+1,this.Ub+1,this.Ba-2,this.Fa-2),(0,D.LV)(this,b,this.sq),this.sq.qa(D.p),b.k(this.sq),this.Pu&&(this.ze=(0,D.JV)(this,b));else{var c=this.BI();b=new D.Te(a,this.Ab,this.Ub,this.Ba,this.Fa);if((1E3>this.H.Yr||!(0,D.Jf)())&&2<=this.Ba&&2<=this.Fa){new D.hg("#FFFFFF");new D.hg("#000000",0.3);this.as&&new D.hg(this.hk,0.15);var d=this.qb(),e=D.I.AM("#FFFFFF",d,
0.7),d=D.I.AM("#000000",d,0.7),f=window.Math.min(this.Ba,this.Fa);4<=f?(b.pa(d),this.pR=new D.Te(a,this.Ab,this.Ub,this.Ba-1,this.Fa-1),this.pR.pa(e),this.pR.qa(D.p),b.k(this.pR),this.Ez=new D.Te(a,this.Ab+1,this.Ub+1,this.Ba-2,this.Fa-2),this.Ez.L(c),this.Ez.qa(D.p),b.k(this.Ez)):2<=f?(b.pa(d),this.Ez=new D.Te(a,this.Ab,this.Ub,this.Ba-1,this.Fa-1),this.Ez.L(c),this.Ez.qa(D.p),b.k(this.Ez)):b.L(c)}else b.L(c)}this.H.ka().Ca(b,this);this.Aa()?b.Lf(D.k):b.setCursor("default");b.zIndex=this.qZ;return b};
D.JV=function(a,b){if("header"!=a.Wk||!a.oy())return D.o;var c=D.o,d=a.Ab,e=a.Ab+a.Ba-1,f=a.Ub+1,g=a.Ub+a.ip;if(12<e-d-2){if(a.Pu){var c=a.H.j(),h=(0,D.E)(a.U),j=a.H.q()._resources,l=h&&j.restoreDownRtl?j.restoreDownRtl:j.restoreDown,m=h&&j.restoreOverRtl?j.restoreOverRtl:j.restoreOver,h=new D.Ue(c,h&&j.restoreRtl?j.restoreRtl:j.restore,0,0,12,12),l=new D.Ue(c,l,0,0,12,12),m=new D.Ue(c,m,0,0,12,12);(0,D.wi)(h);(0,D.wi)(l);(0,D.wi)(m);c=new D.Oe(c,h,l,m);c.la(D.kk,a.Rha,D.p,a)}else c=a.H.j(),h=(0,D.E)(a.U),
j=a.H.q()._resources,l=h&&j.isolateDownRtl?j.isolateDownRtl:j.isolateDown,m=h&&j.isolateOverRtl?j.isolateOverRtl:j.isolateOver,h=new D.Ue(c,h&&j.isolateRtl?j.isolateRtl:j.isolate,0,0,12,12),l=new D.Ue(c,l,0,0,12,12),m=new D.Ue(c,m,0,0,12,12),(0,D.wi)(h),(0,D.wi)(l),(0,D.wi)(m),c=new D.Oe(c,h,l,m),c.la(D.kk,a.Qha,D.p,a);d=(0,D.E)(b.j())?d+1:e-12-1;(0,D.pk)(c,d,(g+f-12)/2);b.k(c);(0,D.Jf)()&&(f=new D.Te(b.j(),-2,-2,16,16),(0,D.wi)(f),c.k(f));(0,D.YH)(a.H.q().skin)?a.H.ka().Ca(c,a):(f=(0,D.nk)(a.H.q(),
a.Pu?"tooltipRestore":"tooltipIsolate","DvtTreemapBundle",a.Pu?"RESTORE":"ISOLATE"),a.H.ka().Ca(c,new D.JR(a,a.getId(),f)))}return c};D.KV=function(a){a.ze&&((0,D.HV)(a,a.ze),a.ze=D.o)};
D.EV.prototype.WO=function(a){var b=(0,D.E)(a.j());if(!this.hD||!a||!this.Wk||"off"==this.Wk)return D.o;var c=this.Fa;if((0,D.bS)(this)>c)return D.o;var d="node"==this.Wk?this.sK:this.XCa;b&&("start"==d?d="end":"end"==d&&(d="start"));var e=this.Ba-6,f=0;this.oy()&&(f=13,e="center"==d?e-2*f:e-f);if(0>=e)return D.o;var g=new D.Kf(this.H.j(),this.hD);g.Ie((0,D.bS)(this));"start"==d?(b?g.ca(this.Ab+4+f):g.ca(this.Ab+4),g.yh()):"center"==d?(g.ca(this.Ab+this.Ba/2),g.Ye()):"end"==d&&(b?g.ca(this.Ab+this.Ba-
4):g.ca(this.Ab+this.Ba-4-f),g.zh());"node"==this.Wk?((0,D.mS)(this,g),c=this.Fa-4,b=D.$e.yH(g),"top"==this.H7?g.va(this.Ub+2):"center"==this.H7?g.va(this.Ub+this.Fa/2-b/2):"bottom"==this.H7&&g.va(this.Ub+this.Fa-2-b)):"header"==this.Wk&&(b=(0,D.ij)()?1:0,g.va(this.Ub+1+this.ip/2+b),g.wf(),(0,D.IV)(this,g,"labelStyle"));if(g!=D.o)return"header"==this.Wk&&this.ju()?((0,D.IV)(this,g,"_drillableLabelStyle"),g.setCursor("pointer"),b=new D.JR(this,this.getId(),D.o,this.De(),this.vi()),b.oda(D.k),this.H.ka().Ca(g,
b)):g.qa(D.p),D.$e.Qb(g,e,c,a)?g:D.o};D.LV=function(a,b,c){var d=a.H.q().nodeDefaults.header;a.qV?(a=a.qb(),c.pa(a),c=D.I.AM(d.borderColor,a,0.5),b.pa(c)):(b.pa(d.borderColor),c.pa(d.backgroundColor))};D.IV=function(a,b,c){var d=[];1>=(0,D.dS)(a)&&d.push(new D.G("font-weight:bold;"));d.push(a.H.q().nodeDefaults.header[c]);a.qV&&("labelStyle"==c||"_drillableLabelStyle"==c)&&d.push(new D.G("color: "+(a.as?"#000000":D.I.tj(a.hk))));a.gla&&d.push(a.gla);b.Ha((0,D.Go)(d))};
D.EV.prototype.gu=function(){!this.ze&&!(0,D.Jf)()&&(this.ze=(0,D.JV)(this,this.G));D.EV.o.gu.call(this)};D.EV.prototype.fu=function(){this.Pu!==D.k&&!(0,D.Jf)()&&(0,D.KV)(this);D.EV.o.fu.call(this)};D.EV.prototype.iH=function(){return this.G?new D.Te(this.H.j(),this.G.ja(),this.G.na(),this.G.getWidth(),this.G.getHeight()):D.o};D.HV=function(a,b){b&&a.G.removeChild(b)};D.x=D.EV.prototype;
D.x.Qha=function(a){this.Pu=D.k;this.Db();var b=this.H,c=b.ka().dd();c&&c.jc();b.hd.push(this);b.q().isolatedNode=this.getId();b.dispatchEvent(new D.GV(this.getId()));b.pX=D.k;b.bq(new D.A(0,0,b.Ga,b.Ta));b.pX=D.p;c=this.ia();b.B7.k(c);(0,D.DV)(b,this);(0,D.KV)(this);this.$m();a&&a.stopPropagation()};
D.x.Rha=function(a){this.Pu=D.p;this.Db();var b=this.H,c=b.hd.pop();b.q().isolatedNode=0<b.hd.length?b.hd[b.hd.length-1].getId():D.o;var d=b.ka().dd();d&&d.jc();d=c.getId();b.iQ=d;b.dispatchEvent(new D.GV);b.pX=D.k;b.bq(new D.A(0,0,b.Ga,b.Ta));b.pX=D.p;(0,D.DV)(b,c);(0,D.KV)(this);this.$m();a&&a.stopPropagation()};D.x.De=function(a,b,c){return a&&a instanceof D.Oe?D.o:D.EV.o.De.call(this,a,b,c)};D.x.vi=function(a){return a&&a instanceof D.Oe?D.o:D.EV.o.vi.call(this,a)};
D.x.Jf=function(a){return a&&a instanceof D.Oe?(0,D.nk)(this.H.q(),this.Pu?"tooltipRestore":"tooltipIsolate","DvtTreemapBundle",this.Pu?"RESTORE":"ISOLATE"):D.o};
D.x.fc=function(){var a=this.H.q(),b=[];this.Aa()&&b.push((0,D.nk)(a,this.Da()?"stateSelected":"stateUnselected","DvtUtilBundle",this.Da()?"STATE_SELECTED":"STATE_UNSELECTED"));this.Pu&&b.push((0,D.nk)(a,"stateIsolated","DvtUtilBundle","STATE_ISOLATED"));this.ju()&&b.push((0,D.nk)(a,"stateDrillable","DvtUtilBundle","STATE_DRILLABLE"));return(0,D.ok)(this.Bc(),b)};D.x.$m=function(){!(0,D.cf)()&&this.G&&this.G.$b("label",this.fc())};
D.qV=function(){this.Init()};D.z.l(D.qV,D.z,"DvtBaseTreemapLayout");D.qV.prototype.Init=function(){this.qZ=0};D.qV.prototype.cr=(0,D.t)();D.rV=function(a,b,c,d,e,f,g){b.qZ=a.qZ;a.qZ++;if(!g||!b.hf()){a=a.Vaa(b.H,(0,D.dS)(b));g=window.Math.round(c+a);var h=window.Math.round(d+a);if(b=b.qT(g,h,window.Math.round(c+e-a)-g,window.Math.round(d+f-a)-h))return b}return new D.A(c,d,e,f)};D.qV.prototype.Vaa=function(a,b){var c=a.q().groupGaps;return"outer"==c?1==b&&2<=a.ut?3:0:"all"==c?b<a.ut?3:0:0};
D.tV=function(){this.Init()};D.z.l(D.tV,D.qV,"DvtSquarifyingLayout");D.tV.prototype.cr=function(a,b,c,d,e,f,g){this.nf(b,c,d,e,f,g?D.p:D.k)};D.tV.prototype.nf=function(a,b,c,d,e,f){b=(0,D.rV)(this,a,b,c,d,e,f);a=a.zc();if(a!=D.o&&0<a.length){c=a;e=b.e*b.g;for(d=d=f=0;d<c.length;d++)f+=0<c[d].Tc()?c[d].Tc():0;e=0==e?0:e/f;for(d=0;d<c.length;d++)f=c[d],f.ME=f.Tc()*e;a=a.slice(0).sort(function(a,b){return a.Tc()-b.Tc()});c=window.Math.min(b.e,b.g);(0,D.uV)(this,a,c,new D.A(b.x,b.y,b.e,b.g))}};
D.uV=function(a,b,c,d){var e=[],f=window.Infinity;if(b==D.o||0==b.length)(0,D.vV)(a,e,c,d);else for(;0<b.length;){var g=b.pop();if(0>g.ME){(0,D.vV)(a,e,c,d);break}e.push(g);var h,j=e,l=c,m=0;h=window.Infinity;for(var n=-window.Infinity,q=0;q<j.length;q++)m+=j[q].ME,h=window.Math.min(h,j[q].ME),n=window.Math.max(n,j[q].ME);j=m*m;l*=l;h=window.Math.max(l*n/j,j/(l*h));if(h>f){b.push(g);e.pop();d=(0,D.vV)(a,e,c,d);(0,D.uV)(a,b,window.Math.min(d.e,d.g),d);break}else if(0==b.length){(0,D.vV)(a,e,c,d);break}else f=
h}};D.vV=function(a,b,c,d){var e=0,f;for(f=0;f<b.length;f++)e+=b[f].ME;var g=d.x,h=d.y;if(c==d.e){e=0==c?0:e/c;for(f=0;f<b.length;f++)c=b[f].ME/e,a.nf(b[f],g,h,c,e,D.p),g+=c;return new D.A(d.x,d.y+e,d.e,d.g-e)}c=0==c?0:e/c;for(f=0;f<b.length;f++)e=b[f].ME/c,a.nf(b[f],g,h,c,e,D.p),h+=e;return new D.A(d.x+c,d.y,d.e-c,d.g)};
D.sV=function(a){this.Init();this.tx=a};D.z.l(D.sV,D.qV,"DvtSliceAndDiceLayout");D.sV.prototype.cr=function(a,b,c,d,e,f,g){this.nf(this.tx,a,b,c,d,e,f,g?D.p:D.k)};
D.sV.prototype.nf=function(a,b,c,d,e,f,g,h){var j=b.q();d=(0,D.rV)(this,c,d,e,f,g,h);c=c.zc();if(c!=D.o){e=d.x;f=d.y;g=d.e;h=d.g;var l=0,m;for(m=0;m<c.length;m++)l+=0<c[m].Tc()?c[m].Tc():0;"on"==j.sorting&&(c=c.slice(0),c.sort(function(a,b){return b.Tc()-a.Tc()}));a&&(0,D.E)(b.j())&&(c=c.slice(0).reverse());for(m=0;m<c.length;m++)if(j=c[m],!(0>=j.Tc())){var n=j.Tc()/l;a?g=d.e*n:h=d.g*n;this.nf(!a,b,j,e,f,g,h,D.p);a?e+=g:f+=h}}};
D.GV=function(a){this.Init("treemapIsolate");this.Xa=a?a:D.o};(0,D.da)("DvtTreemapIsolateEvent",D.GV);D.z.l(D.GV,D.Li,"DvtTreemapIsolateEvent");D.GV.TYPE="treemapIsolate";D.GV.prototype.getId=(0,D.v)("Xa");D.GV.prototype.getId=D.GV.prototype.getId;
D.yV=function(a){this.Init(a)};D.z.l(D.yV,D.gV,"DvtTreemapKeyboardHandler");D.yV.prototype.tg=function(a){var b=D.yV.o.tg.call(this,a);if(!b&&(a=a.keyCode,219==a||221==a))b=D.k;return b};
D.zV=function(a,b,c,d){D.WR.call(this,a,b,c,d)};D.z.l(D.zV,D.WR,"DvtTreemapEventManager");D.zV.prototype.Kh=function(a){var b=D.k;if(13==a.keyCode&&a.ctrlKey){var c=this.dd();c.oy()&&(c.Pu?c.Rha():c.Qha());(0,D.hi)(a)}else b=D.zV.o.Kh.call(this,a);return b};D.zV.prototype.Uba=(0,D.ca)(D.p);
(0,D.Dg)("DvtTreemapBundle",{COLOR:"Color",ISOLATE:"Isolate",OTHER:"Other",RESTORE:"Restore",SIZE:"Size"});
D.xV=function(){this.Init({skyros:D.FV,alta:{}})};D.z.l(D.xV,D.VR,"DvtTreemapDefaults");
D.FV={groupGaps:"outer",nodeDefaults:{header:{backgroundColor:"#FFFFFF",borderColor:"#d6dfe6",hoverBackgroundColor:"#ebeced",hoverOuterColor:"#ebeced",hoverInnerColor:"#d6d7d8",isolate:"auto",labelHalign:"start",labelStyle:new D.G("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 12px;color:#252525;"),selectedBackgroundColor:"#dae9f5",selectedInnerColor:"#FFFFFF",selectedOuterColor:"#000000",useNodeColor:"off",_hoverLabelStyle:new D.G("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 12px;color:#252525;"),
_selectedLabelStyle:new D.G("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 12px;color:#252525;"),_drillableLabelStyle:new D.G("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 12px; color:#145c9e;"),_drillableHoverLabelStyle:new D.G("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 12px; color:#145c9e;"),_drillableSelectedLabelStyle:new D.G("font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 12px; color:#145c9e;")},
hoverColor:"#ebeced",groupLabelDisplay:"header",labelDisplay:"node",labelHalign:"center",labelValign:"center",selectedInnerColor:"#FFFFFF",selectedOuterColor:"#000000"}};

  return D;
});